=== Opentrons/opentrons/shared-data/labware/schemas/2.json
{
  "$id": "opentronsLabwareSchemaV2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "brandData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["brand"],
      "properties": {
        "brand": {
          "type": "string",
          "description": "Brand/manufacturer name"
        },
        "brandId": {
          "type": "array",
          "description": "An array of manufacture numbers pertaining to a given labware",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "description": "URLs for manufacturer page(s)",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "displayCategory": {
      "type": "string",
      "enum": [
        "tipRack",
        "tubeRack",
        "reservoir",
        "trash",
        "wellPlate",
        "aluminumBlock",
        "other"
      ]
    },
    "safeString": {
      "description": "a string safe to use for loadName / namespace. Lowercase-only.",
      "type": "string",
      "pattern": "^[a-z0-9._]+$"
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "version",
    "namespace",
    "metadata",
    "brand",
    "parameters",
    "cornerOffsetFromSlot",
    "ordering",
    "dimensions",
    "wells",
    "groups"
  ],
  "properties": {
    "schemaVersion": {
      "description": "Which schema version a labware is using",
      "type": "number",
      "enum": [2]
    },
    "version": {
      "description": "Version of the labware definition itself (eg myPlate v1/v2/v3). An incrementing integer",
      "type": "integer",
      "minimum": 1
    },
    "namespace": {
      "$ref": "#/definitions/safeString"
    },
    "metadata": {
      "type": "object",
      "description": "Properties used for search and display",
      "additionalProperties": false,
      "required": ["displayName", "displayCategory", "displayVolumeUnits"],
      "properties": {
        "displayName": {
          "description": "Easy to remember name of labware",
          "type": "string"
        },
        "displayCategory": {
          "$ref": "#/definitions/displayCategory",
          "description": "Label(s) used in UI to categorize labware"
        },
        "displayVolumeUnits": {
          "description": "Volume units for display",
          "type": "string",
          "enum": ["ÂµL", "mL", "L"]
        },
        "tags": {
          "type": "array",
          "description": "List of descriptions for a given labware",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "brand": {
      "$ref": "#/definitions/brandData",
      "description": "Real-world labware that the definition is modeled from and/or compatible with"
    },
    "parameters": {
      "type": "object",
      "description": "Internal describers used to determine pipette movement to labware",
      "additionalProperties": false,
      "required": [
        "format",
        "isTiprack",
        "loadName",
        "isMagneticModuleCompatible"
      ],
      "properties": {
        "format": {
          "description": "Property to determine compatibility with multichannel pipette",
          "type": "string",
          "enum": ["96Standard", "384Standard", "trough", "irregular", "trash"]
        },
        "quirks": {
          "description": "Property to classify a specific behavior this labware should have",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isTiprack": {
          "description": "Flag marking whether this labware is a tip rack or not",
          "type": "boolean"
        },
        "tipLength": {
          "description": "Required if this labware is a tip rack. Specifies the total length of one of this rack's tips, from top to bottom, as specified by technical drawings or as measured with calipers.",
          "$ref": "#/definitions/positiveNumber"
        },
        "tipOverlap": {
          "description": "Required if this labware is a tip rack. Specifies how far one of this rack's tips is expected to overlap with the nozzle of a pipette. In other words: tipLength, minus the distance between the bottom of the pipette and the bottom of the tip. A robot's positional calibration may fine-tune this estimate.",
          "$ref": "#/definitions/positiveNumber"
        },
        "loadName": {
          "description": "Name used to reference a labware definition",
          "$ref": "#/definitions/safeString"
        },
        "isMagneticModuleCompatible": {
          "description": "Flag marking whether a labware is compatible by default with the Magnetic Module",
          "type": "boolean"
        },
        "magneticModuleEngageHeight": {
          "description": "Distance to move magnetic module magnets to engage",
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "ordering": {
      "type": "array",
      "description": "Generated array that keeps track of how wells should be ordered in a labware",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1
      }
    },
    "cornerOffsetFromSlot": {
      "type": "object",
      "additionalProperties": false,
      "description": "Distance from left-front-bottom corner of slot to left-front-bottom corner of labware bounding box. Used for labware that spans multiple slots. For labware that does not span multiple slots, x/y/z should all be zero.",
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Outer dimensions of a labware",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "yDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "zDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "xDimension": {
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "wells": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "minProperties": 1,
      "patternProperties": {
        "[A-Z]+[0-9]+": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "shape", "totalLiquidVolume", "x", "y", "z"],
          "oneOf": [
            { "required": ["xDimension", "yDimension"] },
            { "required": ["diameter"] }
          ],
          "not": {
            "anyOf": [
              { "required": ["diameter", "xDimension"] },
              { "required": ["diameter", "yDimension"] }
            ]
          },
          "properties": {
            "depth": {
              "description": "The distance between the top and bottom of this well. If the labware is a tip rack, this will be ignored in favor of tipLength, but the values should match.",
              "$ref": "#/definitions/positiveNumber"
            },
            "x": {
              "description": "x location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "y": {
              "description": "y location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "z": {
              "description": "z location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "totalLiquidVolume": {
              "description": "Total well, tube, or tip volume in microliters",
              "$ref": "#/definitions/positiveNumber"
            },
            "xDimension": {
              "description": "x dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "yDimension": {
              "description": "y dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "diameter": {
              "description": "diameter of circular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "shape": {
              "description": "If 'rectangular', use xDimension and yDimension; if 'circular' use diameter",
              "type": "string",
              "enum": ["rectangular", "circular"]
            }
          }
        }
      }
    },
    "groups": {
      "type": "array",
      "description": "Logical well groupings for metadata/display purposes; changes in groups do not affect protocol execution",
      "items": {
        "type": "object",
        "required": ["wells", "metadata"],
        "additionalProperties": false,
        "properties": {
          "wells": {
            "type": "array",
            "description": "An array of wells that contain the same metadata",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "metadata": {
            "type": "object",
            "description": "Metadata specific to a grid of wells in a labware",
            "required": [],
            "additionalProperties": false,
            "properties": {
              "displayName": {
                "type": "string",
                "description": "User-readable name for the well group"
              },
              "displayCategory": {
                "$ref": "#/definitions/displayCategory",
                "description": "Label(s) used in UI to categorize well groups"
              },
              "wellBottomShape": {
                "type": "string",
                "description": "Bottom shape of the well for UI purposes",
                "enum": ["flat", "u", "v"]
              }
            }
          },
          "brand": {
            "$ref": "#/definitions/brandData",
            "description": "Brand data for the well group (e.g. for tubes)"
          }
        }
      }
    }
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/usascientific_12_reservoir_22ml/1.json
{
  "ordering": [
    ["A1"],
    ["A2"],
    ["A3"],
    ["A4"],
    ["A5"],
    ["A6"],
    ["A7"],
    ["A8"],
    ["A9"],
    ["A10"],
    ["A11"],
    ["A12"]
  ],
  "schemaVersion": 2,
  "version": 1,
  "namespace": "opentrons",
  "metadata": {
    "displayName": "USA Scientific 12 Well Reservoir 22 mL",
    "displayVolumeUnits": "mL",
    "displayCategory": "reservoir",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.8,
    "zDimension": 44.45
  },
  "parameters": {
    "format": "trough",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "usascientific_12_reservoir_22ml",
    "quirks": ["centerMultichannelOnWells", "touchTipDisabled"]
  },
  "wells": {
    "A1": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 13.94,
      "y": 42.9,
      "z": 2.29
    },
    "A2": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 23.03,
      "y": 42.9,
      "z": 2.29
    },
    "A3": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 32.12,
      "y": 42.9,
      "z": 2.29
    },
    "A4": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 41.21,
      "y": 42.9,
      "z": 2.29
    },
    "A5": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 50.3,
      "y": 42.9,
      "z": 2.29
    },
    "A6": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 59.39,
      "y": 42.9,
      "z": 2.29
    },
    "A7": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 68.48,
      "y": 42.9,
      "z": 2.29
    },
    "A8": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 77.57,
      "y": 42.9,
      "z": 2.29
    },
    "A9": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 86.66,
      "y": 42.9,
      "z": 2.29
    },
    "A10": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 95.75,
      "y": 42.9,
      "z": 2.29
    },
    "A11": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 104.84,
      "y": 42.9,
      "z": 2.29
    },
    "A12": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 113.93,
      "y": 42.9,
      "z": 2.29
    }
  },
  "groups": [
    {
      "wells": [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12"
      ],
      "metadata": {
        "wellBottomShape": "v"
      }
    }
  ],
  "brand": {
    "brand": "USA Scientific",
    "brandId": ["1061-8150"],
    "links": [
      "https://www.usascientific.com/12-channel-automation-reservoir.aspx"
    ]
  },
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/opentrons_10_tuberack_nest_4x50ml_6x15ml_conical/1.json
{
  "wells": {
    "A1": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 13.88,
      "y": 67.75,
      "z": 6.85
    },
    "B1": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 13.88,
      "y": 42.75,
      "z": 6.85
    },
    "C1": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 13.88,
      "y": 17.75,
      "z": 6.85
    },
    "A2": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 38.88,
      "y": 67.75,
      "z": 6.85
    },
    "B2": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 38.88,
      "y": 42.75,
      "z": 6.85
    },
    "C2": {
      "totalLiquidVolume": 15000,
      "diameter": 15.5,
      "shape": "circular",
      "depth": 117.8,
      "x": 38.88,
      "y": 17.75,
      "z": 6.85
    },
    "A3": {
      "totalLiquidVolume": 50000,
      "diameter": 27.95,
      "shape": "circular",
      "depth": 113.05,
      "x": 71.38,
      "y": 60.25,
      "z": 7.3
    },
    "B3": {
      "totalLiquidVolume": 50000,
      "diameter": 27.95,
      "shape": "circular",
      "depth": 113.05,
      "x": 71.38,
      "y": 25.25,
      "z": 7.3
    },
    "A4": {
      "totalLiquidVolume": 50000,
      "diameter": 27.95,
      "shape": "circular",
      "depth": 113.05,
      "x": 106.38,
      "y": 60.25,
      "z": 7.3
    },
    "B4": {
      "totalLiquidVolume": 50000,
      "diameter": 27.95,
      "shape": "circular",
      "depth": 113.05,
      "x": 106.38,
      "y": 25.25,
      "z": 7.3
    }
  },
  "groups": [
    {
      "metadata": {
        "displayName": "NEST 6x15 mL Conical",
        "displayCategory": "tubeRack",
        "wellBottomShape": "v"
      },
      "brand": {
        "brand": "NEST",
        "brandId": ["601052"],
        "links": ["http://www.cell-nest.com/page94?_l=en&product_id=110"]
      },
      "wells": ["A1", "B1", "C1", "A2", "B2", "C2"]
    },
    {
      "metadata": {
        "displayName": "NEST 4x50 mL Conical",
        "displayCategory": "tubeRack",
        "wellBottomShape": "v"
      },
      "brand": {
        "brand": "NEST",
        "brandId": ["602052"],
        "links": ["http://www.cell-nest.com/page94?_l=en&product_id=110"]
      },
      "wells": ["A3", "B3", "A4", "B4"]
    }
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": [
      "https://shop.opentrons.com/collections/opentrons-tips/products/tube-rack-set-1"
    ]
  },
  "metadata": {
    "displayName": "Opentrons 10 Tube Rack with NEST 4x50 mL, 6x15 mL Conical",
    "displayCategory": "tubeRack",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.48,
    "zDimension": 124.65
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_10_tuberack_nest_4x50ml_6x15ml_conical"
  },
  "ordering": [
    ["A1", "B1", "C1"],
    ["A2", "B2", "C2"],
    ["A3", "B3"],
    ["A4", "B4"]
  ],
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/opentrons_24_tuberack_nest_2ml_snapcap/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": [
      "https://shop.opentrons.com/collections/opentrons-tips/products/tube-rack-set-1"
    ]
  },
  "metadata": {
    "displayName": "Opentrons 24 Tube Rack with NEST 2 mL Snapcap",
    "displayCategory": "tubeRack",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.75,
    "yDimension": 85.5,
    "zDimension": 79.45
  },
  "wells": {
    "A1": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 75.43,
      "z": 40.17
    },
    "B1": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 56.15,
      "z": 40.17
    },
    "C1": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 36.87,
      "z": 40.17
    },
    "D1": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 18.21,
      "y": 17.59,
      "z": 40.17
    },
    "A2": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 75.43,
      "z": 40.17
    },
    "B2": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 56.15,
      "z": 40.17
    },
    "C2": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 36.87,
      "z": 40.17
    },
    "D2": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 38.1,
      "y": 17.59,
      "z": 40.17
    },
    "A3": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 75.43,
      "z": 40.17
    },
    "B3": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 56.15,
      "z": 40.17
    },
    "C3": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 36.87,
      "z": 40.17
    },
    "D3": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 57.99,
      "y": 17.59,
      "z": 40.17
    },
    "A4": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 75.43,
      "z": 40.17
    },
    "B4": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 56.15,
      "z": 40.17
    },
    "C4": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 36.87,
      "z": 40.17
    },
    "D4": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 77.88,
      "y": 17.59,
      "z": 40.17
    },
    "A5": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 75.43,
      "z": 40.17
    },
    "B5": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 56.15,
      "z": 40.17
    },
    "C5": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 36.87,
      "z": 40.17
    },
    "D5": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 97.77,
      "y": 17.59,
      "z": 40.17
    },
    "A6": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 75.43,
      "z": 40.17
    },
    "B6": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 56.15,
      "z": 40.17
    },
    "C6": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 36.87,
      "z": 40.17
    },
    "D6": {
      "depth": 39.28,
      "shape": "circular",
      "diameter": 10.18,
      "totalLiquidVolume": 2000,
      "x": 117.66,
      "y": 17.59,
      "z": 40.17
    }
  },
  "groups": [
    {
      "metadata": {
        "displayName": "NEST 24x2 mL Snapcap",
        "displayCategory": "tubeRack",
        "wellBottomShape": "u"
      },
      "brand": {
        "brand": "NEST",
        "brandId": ["620611", "620011"],
        "links": [
          "http://www.cell-nest.com/page94?_l=en&product_id=108&product_category=84"
        ]
      },
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ]
    }
  ],
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_24_tuberack_nest_2ml_snapcap"
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}
