=== Opentrons/opentrons/shared-data/labware/schemas/2.json
{
  "$id": "opentronsLabwareSchemaV2",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "brandData": {
      "type": "object",
      "additionalProperties": false,
      "required": ["brand"],
      "properties": {
        "brand": {
          "type": "string",
          "description": "Brand/manufacturer name"
        },
        "brandId": {
          "type": "array",
          "description": "An array of manufacture numbers pertaining to a given labware",
          "items": {
            "type": "string"
          }
        },
        "links": {
          "type": "array",
          "description": "URLs for manufacturer page(s)",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "displayCategory": {
      "type": "string",
      "enum": [
        "tipRack",
        "tubeRack",
        "reservoir",
        "trash",
        "wellPlate",
        "aluminumBlock",
        "other"
      ]
    },
    "safeString": {
      "description": "a string safe to use for loadName / namespace. Lowercase-only.",
      "type": "string",
      "pattern": "^[a-z0-9._]+$"
    }
  },
  "type": "object",
  "additionalProperties": false,
  "required": [
    "schemaVersion",
    "version",
    "namespace",
    "metadata",
    "brand",
    "parameters",
    "cornerOffsetFromSlot",
    "ordering",
    "dimensions",
    "wells",
    "groups"
  ],
  "properties": {
    "schemaVersion": {
      "description": "Which schema version a labware is using",
      "type": "number",
      "enum": [2]
    },
    "version": {
      "description": "Version of the labware definition itself (eg myPlate v1/v2/v3). An incrementing integer",
      "type": "integer",
      "minimum": 1
    },
    "namespace": {
      "$ref": "#/definitions/safeString"
    },
    "metadata": {
      "type": "object",
      "description": "Properties used for search and display",
      "additionalProperties": false,
      "required": ["displayName", "displayCategory", "displayVolumeUnits"],
      "properties": {
        "displayName": {
          "description": "Easy to remember name of labware",
          "type": "string"
        },
        "displayCategory": {
          "$ref": "#/definitions/displayCategory",
          "description": "Label(s) used in UI to categorize labware"
        },
        "displayVolumeUnits": {
          "description": "Volume units for display",
          "type": "string",
          "enum": ["ÂµL", "mL", "L"]
        },
        "tags": {
          "type": "array",
          "description": "List of descriptions for a given labware",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "brand": {
      "$ref": "#/definitions/brandData",
      "description": "Real-world labware that the definition is modeled from and/or compatible with"
    },
    "parameters": {
      "type": "object",
      "description": "Internal describers used to determine pipette movement to labware",
      "additionalProperties": false,
      "required": [
        "format",
        "isTiprack",
        "loadName",
        "isMagneticModuleCompatible"
      ],
      "properties": {
        "format": {
          "description": "Property to determine compatibility with multichannel pipette",
          "type": "string",
          "enum": ["96Standard", "384Standard", "trough", "irregular", "trash"]
        },
        "quirks": {
          "description": "Property to classify a specific behavior this labware should have",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "isTiprack": {
          "description": "Flag marking whether this labware is a tip rack or not",
          "type": "boolean"
        },
        "tipLength": {
          "description": "Required if this labware is a tip rack. Specifies the total length of one of this rack's tips, from top to bottom, as specified by technical drawings or as measured with calipers.",
          "$ref": "#/definitions/positiveNumber"
        },
        "tipOverlap": {
          "description": "Required if this labware is a tip rack. Specifies how far one of this rack's tips is expected to overlap with the nozzle of a pipette. In other words: tipLength, minus the distance between the bottom of the pipette and the bottom of the tip. A robot's positional calibration may fine-tune this estimate.",
          "$ref": "#/definitions/positiveNumber"
        },
        "loadName": {
          "description": "Name used to reference a labware definition",
          "$ref": "#/definitions/safeString"
        },
        "isMagneticModuleCompatible": {
          "description": "Flag marking whether a labware is compatible by default with the Magnetic Module",
          "type": "boolean"
        },
        "magneticModuleEngageHeight": {
          "description": "Distance to move magnetic module magnets to engage",
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "ordering": {
      "type": "array",
      "description": "Generated array that keeps track of how wells should be ordered in a labware",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 1
      }
    },
    "cornerOffsetFromSlot": {
      "type": "object",
      "additionalProperties": false,
      "description": "Distance from left-front-bottom corner of slot to left-front-bottom corner of labware bounding box. Used for labware that spans multiple slots. For labware that does not span multiple slots, x/y/z should all be zero.",
      "required": ["x", "y", "z"],
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "description": "Outer dimensions of a labware",
      "required": ["xDimension", "yDimension", "zDimension"],
      "properties": {
        "yDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "zDimension": {
          "$ref": "#/definitions/positiveNumber"
        },
        "xDimension": {
          "$ref": "#/definitions/positiveNumber"
        }
      }
    },
    "wells": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "minProperties": 1,
      "patternProperties": {
        "[A-Z]+[0-9]+": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "shape", "totalLiquidVolume", "x", "y", "z"],
          "oneOf": [
            { "required": ["xDimension", "yDimension"] },
            { "required": ["diameter"] }
          ],
          "not": {
            "anyOf": [
              { "required": ["diameter", "xDimension"] },
              { "required": ["diameter", "yDimension"] }
            ]
          },
          "properties": {
            "depth": {
              "description": "The distance between the top and bottom of this well. If the labware is a tip rack, this will be ignored in favor of tipLength, but the values should match.",
              "$ref": "#/definitions/positiveNumber"
            },
            "x": {
              "description": "x location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "y": {
              "description": "y location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "z": {
              "description": "z location of center-bottom of well in reference to left-front-bottom of labware",
              "$ref": "#/definitions/positiveNumber"
            },
            "totalLiquidVolume": {
              "description": "Total well, tube, or tip volume in microliters",
              "$ref": "#/definitions/positiveNumber"
            },
            "xDimension": {
              "description": "x dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "yDimension": {
              "description": "y dimension of rectangular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "diameter": {
              "description": "diameter of circular wells",
              "$ref": "#/definitions/positiveNumber"
            },
            "shape": {
              "description": "If 'rectangular', use xDimension and yDimension; if 'circular' use diameter",
              "type": "string",
              "enum": ["rectangular", "circular"]
            }
          }
        }
      }
    },
    "groups": {
      "type": "array",
      "description": "Logical well groupings for metadata/display purposes; changes in groups do not affect protocol execution",
      "items": {
        "type": "object",
        "required": ["wells", "metadata"],
        "additionalProperties": false,
        "properties": {
          "wells": {
            "type": "array",
            "description": "An array of wells that contain the same metadata",
            "items": {
              "type": "string"
            },
            "minItems": 1
          },
          "metadata": {
            "type": "object",
            "description": "Metadata specific to a grid of wells in a labware",
            "required": [],
            "additionalProperties": false,
            "properties": {
              "displayName": {
                "type": "string",
                "description": "User-readable name for the well group"
              },
              "displayCategory": {
                "$ref": "#/definitions/displayCategory",
                "description": "Label(s) used in UI to categorize well groups"
              },
              "wellBottomShape": {
                "type": "string",
                "description": "Bottom shape of the well for UI purposes",
                "enum": ["flat", "u", "v"]
              }
            }
          },
          "brand": {
            "$ref": "#/definitions/brandData",
            "description": "Brand data for the well group (e.g. for tubes)"
          }
        }
      }
    }
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/opentrons_24_aluminumblock_nest_1.5ml_snapcap/1.json
{
  "ordering": [
    ["A1", "B1", "C1", "D1"],
    ["A2", "B2", "C2", "D2"],
    ["A3", "B3", "C3", "D3"],
    ["A4", "B4", "C4", "D4"],
    ["A5", "B5", "C5", "D5"],
    ["A6", "B6", "C6", "D6"]
  ],
  "brand": {
    "brand": "Opentrons",
    "brandId": [],
    "links": [
      "https://shop.opentrons.com/collections/opentrons-tips/products/tube-rack-set-1"
    ]
  },
  "metadata": {
    "displayName": "Opentrons 24 Well Aluminum Block with NEST 1.5 mL Snapcap",
    "displayCategory": "aluminumBlock",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.75,
    "yDimension": 85.5,
    "zDimension": 43.7
  },
  "wells": {
    "A1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 20.75,
      "y": 68.62,
      "z": 5.8
    },
    "B1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 20.75,
      "y": 51.37,
      "z": 5.8
    },
    "C1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 20.75,
      "y": 34.12,
      "z": 5.8
    },
    "D1": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 20.75,
      "y": 16.87,
      "z": 5.8
    },
    "A2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38,
      "y": 68.62,
      "z": 5.8
    },
    "B2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38,
      "y": 51.37,
      "z": 5.8
    },
    "C2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38,
      "y": 34.12,
      "z": 5.8
    },
    "D2": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 38,
      "y": 16.87,
      "z": 5.8
    },
    "A3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 55.25,
      "y": 68.62,
      "z": 5.8
    },
    "B3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 55.25,
      "y": 51.37,
      "z": 5.8
    },
    "C3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 55.25,
      "y": 34.12,
      "z": 5.8
    },
    "D3": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 55.25,
      "y": 16.87,
      "z": 5.8
    },
    "A4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 72.5,
      "y": 68.62,
      "z": 5.8
    },
    "B4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 72.5,
      "y": 51.37,
      "z": 5.8
    },
    "C4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 72.5,
      "y": 34.12,
      "z": 5.8
    },
    "D4": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 72.5,
      "y": 16.87,
      "z": 5.8
    },
    "A5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 89.75,
      "y": 68.62,
      "z": 5.8
    },
    "B5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 89.75,
      "y": 51.37,
      "z": 5.8
    },
    "C5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 89.75,
      "y": 34.12,
      "z": 5.8
    },
    "D5": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 89.75,
      "y": 16.87,
      "z": 5.8
    },
    "A6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 107,
      "y": 68.62,
      "z": 5.8
    },
    "B6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 107,
      "y": 51.37,
      "z": 5.8
    },
    "C6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 107,
      "y": 34.12,
      "z": 5.8
    },
    "D6": {
      "depth": 37.9,
      "shape": "circular",
      "diameter": 10.2,
      "totalLiquidVolume": 1500,
      "x": 107,
      "y": 16.87,
      "z": 5.8
    }
  },
  "groups": [
    {
      "metadata": {
        "displayName": "NEST 24x1.5 mL Snapcap",
        "displayCategory": "tubeRack",
        "wellBottomShape": "v"
      },
      "brand": {
        "brand": "NEST",
        "brandId": ["615601", "615001"],
        "links": [
          "http://www.cell-nest.com/page94?_l=en&product_id=108&product_category=84"
        ]
      },
      "wells": [
        "A1",
        "B1",
        "C1",
        "D1",
        "A2",
        "B2",
        "C2",
        "D2",
        "A3",
        "B3",
        "C3",
        "D3",
        "A4",
        "B4",
        "C4",
        "D4",
        "A5",
        "B5",
        "C5",
        "D5",
        "A6",
        "B6",
        "C6",
        "D6"
      ]
    }
  ],
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "opentrons_24_aluminumblock_nest_1.5ml_snapcap"
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/nest_1_reservoir_195ml/1.json
{
  "ordering": [["A1"]],
  "brand": {
    "brand": "NEST",
    "brandId": ["360103"],
    "links": ["http://www.cell-nest.com/page94?_l=en&product_id=102"]
  },
  "metadata": {
    "displayName": "NEST 1 Well Reservoir 195 mL",
    "displayCategory": "reservoir",
    "displayVolumeUnits": "mL",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.48,
    "zDimension": 31.4
  },
  "wells": {
    "A1": {
      "depth": 25,
      "shape": "rectangular",
      "xDimension": 106.8,
      "yDimension": 71.2,
      "totalLiquidVolume": 195000,
      "x": 63.88,
      "y": 42.74,
      "z": 4.55
    }
  },
  "groups": [
    {
      "metadata": {
        "wellBottomShape": "v"
      },
      "wells": ["A1"]
    }
  ],
  "parameters": {
    "format": "trough",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "quirks": ["centerMultichannelOnWells", "touchTipDisabled"],
    "loadName": "nest_1_reservoir_195ml"
  },
  "namespace": "opentrons",
  "version": 1,
  "schemaVersion": 2,
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/hardware-testing/hardware_testing/gravimetric/radwag_pipette_calibration_vial.json
{
    "ordering": [["A1"]],
    "brand": {"brand": "Radwag", "brandId": ["AXA11"]},
    "metadata": {
        "displayName": "Radwag Pipette Calibration Vial",
        "displayCategory": "tubeRack",
        "displayVolumeUnits": "ÂµL",
        "tags": []
    },
    "dimensions": {"xDimension": 128, "yDimension": 86, "zDimension": 86},
    "wells": {
        "A1": {
            "depth": 40,
            "totalLiquidVolume": 2152.38,
            "shape": "circular",
            "diameter": 14.5,
            "x": 64,
            "y": 43,
            "z": 46
        }
    },
    "groups": [
        {
            "brand": {"brand": "Radwag", "brandId": ["AXA11"]},
            "metadata": {"wellBottomShape": "flat", "displayCategory": "tubeRack"},
            "wells": ["A1"]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isTiprack": false,
        "isMagneticModuleCompatible": false,
        "loadName": "radwag_pipette_calibration_vial"
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {"x": 0, "y": 0, "z": 0}
}

=== Opentrons/opentrons/shared-data/labware/fixtures/2/fixture_regular_example_2.json
{
  "metadata": {
    "displayName": "fake labware 2",
    "displayCategory": "wellPlate",
    "displayVolumeUnits": "mL"
  },
  "brand": {
    "brand": "generic"
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "loadName": "fixture_regular_example_2",
    "isMagneticModuleCompatible": false
  },
  "schemaVersion": 2,
  "version": 1,
  "namespace": "fixture",
  "dimensions": {
    "xDimension": 40,
    "yDimension": 40,
    "zDimension": 40
  },
  "ordering": [["A1", "B1", "C1"], ["A2", "B2", "C2"]],
  "wells": {
    "A1": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 10,
      "y": 30,
      "z": 10,
      "shape": "circular"
    },
    "B1": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 10,
      "y": 20,
      "z": 10,
      "shape": "circular"
    },
    "C1": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 10,
      "y": 10,
      "z": 10,
      "shape": "circular"
    },
    "A2": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 20,
      "y": 30,
      "z": 10,
      "shape": "circular"
    },
    "B2": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 20,
      "y": 20,
      "z": 10,
      "shape": "circular"
    },
    "C2": {
      "depth": 30,
      "totalLiquidVolume": 1000,
      "diameter": 30,
      "x": 20,
      "y": 10,
      "z": 10,
      "shape": "circular"
    }
  },
  "groups": [
    {
      "wells": ["A1", "B1", "C1", "A2", "B2", "C2"],
      "metadata": {}
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/shared-data/labware/definitions/2/corning_6_wellplate_16.8ml_flat/1.json
{
  "ordering": [["A1", "B1"], ["A2", "B2"], ["A3", "B3"]],
  "metadata": {
    "displayName": "Corning 6 Well Plate 16.8 mL Flat",
    "displayVolumeUnits": "mL",
    "displayCategory": "wellPlate",
    "tags": []
  },
  "schemaVersion": 2,
  "version": 1,
  "namespace": "opentrons",
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.47,
    "zDimension": 20.27
  },
  "parameters": {
    "format": "irregular",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "corning_6_wellplate_16.8ml_flat"
  },
  "wells": {
    "B1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 24.76,
      "y": 23.16,
      "z": 2.87
    },
    "A1": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 24.76,
      "y": 62.28,
      "z": 2.87
    },
    "B2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 63.88,
      "y": 23.16,
      "z": 2.87
    },
    "A2": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 63.88,
      "y": 62.28,
      "z": 2.87
    },
    "B3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 103,
      "y": 23.16,
      "z": 2.87
    },
    "A3": {
      "shape": "circular",
      "depth": 17.4,
      "diameter": 35.43,
      "totalLiquidVolume": 16800,
      "x": 103,
      "y": 62.28,
      "z": 2.87
    }
  },
  "brand": {
    "brand": "Corning",
    "brandId": ["3335", "3506", "3516", "3471"],
    "links": [
      "https://ecatalog.corning.com/life-sciences/b2c/US/en/Microplates/Assay-Microplates/96-Well-Microplates/Costar%C2%AE-Multiple-Well-Cell-Culture-Plates/p/3335"
    ]
  },
  "groups": [
    {
      "wells": ["A1", "B1", "A2", "B2", "A3", "B3"],
      "metadata": {
        "wellBottomShape": "flat"
      }
    }
  ],
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}

=== Opentrons/opentrons/robot-server/tests/opentrons/protocols/fixtures/bundled_protocols/simple_bundle/custom_labware.json
{
  "ordering": [
    ["A1"],
    ["A2"],
    ["A3"],
    ["A4"],
    ["A5"],
    ["A6"],
    ["A7"],
    ["A8"],
    ["A9"],
    ["A10"],
    ["A11"],
    ["A12"]
  ],
  "schemaVersion": 2,
  "version": 1,
  "namespace": "custom_beta",
  "metadata": {
    "displayName": "FAKE example labware",
    "displayVolumeUnits": "mL",
    "displayCategory": "reservoir",
    "tags": []
  },
  "dimensions": {
    "xDimension": 127.76,
    "yDimension": 85.8,
    "zDimension": 44.45
  },
  "parameters": {
    "format": "trough",
    "isTiprack": false,
    "isMagneticModuleCompatible": false,
    "loadName": "custom_labware",
    "quirks": ["centerMultichannelOnWells"]
  },
  "wells": {
    "A1": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 13.94,
      "y": 42.9,
      "z": 2.29
    },
    "A2": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 23.03,
      "y": 42.9,
      "z": 2.29
    },
    "A3": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 32.12,
      "y": 42.9,
      "z": 2.29
    },
    "A4": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 41.21,
      "y": 42.9,
      "z": 2.29
    },
    "A5": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 50.3,
      "y": 42.9,
      "z": 2.29
    },
    "A6": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 59.39,
      "y": 42.9,
      "z": 2.29
    },
    "A7": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 68.48,
      "y": 42.9,
      "z": 2.29
    },
    "A8": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 77.57,
      "y": 42.9,
      "z": 2.29
    },
    "A9": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 86.66,
      "y": 42.9,
      "z": 2.29
    },
    "A10": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 95.75,
      "y": 42.9,
      "z": 2.29
    },
    "A11": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 104.84,
      "y": 42.9,
      "z": 2.29
    },
    "A12": {
      "shape": "rectangular",
      "depth": 42.16,
      "xDimension": 8.33,
      "yDimension": 71.88,
      "totalLiquidVolume": 22000,
      "x": 113.93,
      "y": 42.9,
      "z": 2.29
    }
  },
  "groups": [
    {
      "wells": [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12"
      ],
      "metadata": {
        "wellBottomShape": "v"
      }
    }
  ],
  "brand": {
    "brand": "Fake",
    "brandId": ["123"],
    "links": []
  },
  "cornerOffsetFromSlot": {
    "x": 0,
    "y": 0,
    "z": 0
  }
}
