=== Opentrons/opentrons/shared-data/labware-json-schema/labware-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    }
  },

  "type": "object",
  "additionalProperties": false,
  "required": ["otId", "deprecated", "metadata","parameters", "ordering", "dimensions", "wells"],
  "properties": {
    "otId": {
      "type": "number"
    },
    "deprecated": {
      "type": "boolean"
    },
    "metadata": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "displayCategory"],
      "properties": {
        "name": {
          "type": "string"
        },
        "displayCategory": {
          "type": "string"
        },
        "displayLengthUnits": {
          "type": "string"
        },
        "displayVolumeUnits": {
          "type": "string"
        }
      }
    },
    "vendor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "sku": {
          "type": "string"
        },
        "vendor": {
          "type": "string"
        }
      }

    },
    "parameters": {
      "type": "object",
      "additionalProperties": false,
      "required": ["format", "isTiprack"],
      "properties": {
        "format": {
          "type": "string"
        },
        "isTiprack": {
          "type": "boolean"
        },
        "tipLength": {
          "$ref": "#/definitions/positiveNumber"
        },
        "wellShape": {
          "type": "string"
        }
      }

    },
    "ordering": {
      "type": "array",
      "description": "",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    },
    "dimensions": {
      "type": "object",
      "additionalProperties": false,
      "required": ["overallWidth", "overallHeight", "overallLength", "offsetX", "offsetY", "offsetZ"],
      "properties": {
        "overallWidth": {
          "$ref": "#/definitions/positiveNumber"
        },
        "overallHeight": {
          "$ref": "#/definitions/positiveNumber"
        },
        "overallLength": {
          "$ref": "#/definitions/positiveNumber"
        },
        "offsetX": {
          "$ref": "#/definitions/positiveNumber"
        },
        "offsetY": {
          "$ref": "#/definitions/positiveNumber"
        },
        "offsetZ": {
          "$ref": "#/definitions/positiveNumber"
        }
      }

    },
    "wells": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "object",
          "additionalProperties": false,
          "required": ["depth", "x", "y", "z"],
          "oneOf": [
            {"required": ["width", "length"]},
            {"required": ["diameter"]}
          ],
          "not": {"anyOf": [
                    {"required": ["diameter", "width"]},
                    {"required": ["diameter", "length"]}
          ]},
          "properties": {
            "depth": {"$ref": "#/definitions/positiveNumber"},
            "x": {"$ref": "#/definitions/positiveNumber"},
            "y": {"$ref": "#/definitions/positiveNumber"},
            "z": {"$ref": "#/definitions/positiveNumber"},
            "totalLiquidVolume": {"$ref": "#/definitions/positiveNumber"},
            "width": {"$ref": "#/definitions/positiveNumber"},
            "length": {"$ref": "#/definitions/positiveNumber"},
            "diameter": {"$ref": "#/definitions/positiveNumber"}

          }
        }
      }

    }

  }

}

=== Opentrons/opentrons/shared-data/js/labwareTools/__tests__/example.json
{
 "otId": 1,
 "deprecated": false,
 "metadata": {
   "name": "fake labware",
   "displayCategory": "wellPlate",
   "displayVolumeUnits": "uL",
   "displayLengthUnits": "mm"
 },
 "vendor": {
   "sku": "t40u9sernisofsea",
   "vendor": "opentrons"
 },
 "parameters": {
   "format": "96Standard",
   "isTiprack": false,
   "wellShape": "circular"
 },
 "dimensions": {
   "overallLength": 50,
   "overallWidth": 50,
   "overallHeight": 50,
   "offsetX":10,
   "offsetY":10,
   "offsetZ":5
 },
 "ordering": [["A1"], ["A2"]],
 "wells": {
   "A1":{
     "depth": 40,
     "totalLiquidVolume": 100,
     "diameter": 30,
     "x": 0,
     "y": 0,
     "z": 0

   },
   "A2":{
     "depth": 40,
     "totalLiquidVolume": 100,
     "diameter": 30,
     "x": 10,
     "y": 0,
     "z": 0
     }}


}
