=== Opentrons/opentrons/shared-data/protocol/schemas/2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pipetteName": {
      "description": "Name of a pipette. Does not contain info about specific model/version. Should match keys in pipetteNameSpecs.json file",
      "type": "string",
      "enum": [
        "p10_single",
        "p10_multi",
        "p50_single",
        "p50_multi",
        "p300_single",
        "p300_multi",
        "p1000_single",
        "p1000_multi"
      ]
    },
    "pipette-model": {
      "description": "DEPRECATED. Exists to support backwards compatibility",
      "type": "string",
      "$comment": "TODO: Ian 2018-11-06 remove this def and every usage of it",
      "enum": [
        "p10_single_v1",
        "p10_multi_v1",
        "p50_single_v1",
        "p50_multi_v1",
        "p300_single_v1",
        "p300_multi_v1",
        "p1000_single_v1",
        "p1000_multi_v1",

        "p10_single_v1.3",
        "p10_multi_v1.3",
        "p50_single_v1.3",
        "p50_multi_v1.3",
        "p300_single_v1.3",
        "p300_multi_v1.3",
        "p1000_single_v1.3",
        "p1000_multi_v1.3"
      ]
    },

    "mm-offset": {
      "description": "Millimeters for pipette location offsets",
      "type": "number"
    },

    "flow-rate-for-pipettes": {
      "description": "Flow rate in mm/sec for each pipette model used in the protocol",
      "type": "object",
      "propertyNames": { "$ref": "#/definitions/pipetteName" },
      "patternProperties": { ".*": { "type": "number" } },
      "additionalProperties": false
    },

    "flow-rate-params": {
      "properties": {
        "flow-rate": {
          "description": "Flow rate for aspirate/dispense. If omitted, defaults to the corresponding values in \"default-values\"",
          "type": "number"
        }
      }
    },

    "offsetFromBottomMm": {
      "description": "Offset from bottom of well in millimeters",
      "properties": {
        "offsetFromBottomMm": { "$ref": "#/definitions/mm-offset" }
      }
    },

    "pipette-access-params": {
      "required": ["pipette", "labware", "well"],
      "properties": {
        "pipette": {
          "type": "string"
        },
        "labware": {
          "type": "string"
        },
        "well": {
          "type": "string"
        }
      }
    },

    "volume-params": {
      "required": ["volume"],
      "volume": {
        "type": "number"
      }
    },

    "slot": {
      "description": "Slot on the deck of an OT-2 robot",
      "type": "string",
      "enum": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
    }
  },

  "type": "object",
  "additionalProperties": false,
  "required": [
    "protocol-schema",
    "default-values",
    "metadata",
    "robot",
    "pipettes",
    "labware",
    "procedure"
  ],
  "properties": {
    "protocol-schema": {
      "description": "A version string for the Opentrons JSON Protocol schema being used. \"<major>.<minor>.<patch>\"",
      "type": "string"
    },

    "metadata": {
      "description": "Optional metadata about the protocol",
      "type": "object",

      "properties": {
        "protocol-name": {
          "description": "A short, human-readable name for the protocol",
          "type": "string"
        },
        "author": {
          "description": "The author or organization who created the protocol",
          "type": "string"
        },
        "description": {
          "description": "A text description of the protocol. For guidelines about how to write a good description, see (TODO WRITE DOCS & LINK HERE)",
          "type": ["string", "null"]
        },

        "created": {
          "description": "UNIX timestamp when this file was created",
          "type": "number"
        },
        "last-modified": {
          "description": "UNIX timestamp when this file was last modified",
          "type": ["number", "null"]
        },

        "category": {
          "description": "Category of protocol (eg, \"Basic Pipetting\")",
          "type": ["string", "null"]
        },
        "subcategory": {
          "description": "Subcategory of protocol (eg, \"Cell Plating\")",
          "type": ["string", "null"]
        },
        "tags": {
          "description": "Tags to be used in searching for this protocol",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },

    "default-values": {
      "description": "Default values required for protocol execution",
      "type": "object",
      "$note": "TODO: Ian 2018-10-29 make touch-tip-mm-from-top required (breaking change)",
      "required": [
        "aspirate-flow-rate",
        "dispense-flow-rate",
        "aspirate-mm-from-bottom",
        "dispense-mm-from-bottom"
      ],
      "properties": {
        "aspirate-flow-rate": {
          "$ref": "#/definitions/flow-rate-for-pipettes"
        },
        "dispense-flow-rate": {
          "$ref": "#/definitions/flow-rate-for-pipettes"
        },
        "aspirate-mm-from-bottom": { "$ref": "#/definitions/mm-offset" },
        "dispense-mm-from-bottom": { "$ref": "#/definitions/mm-offset" },
        "touch-tip-mm-from-top": { "$ref": "#/definitions/mm-offset" }
      }
    },

    "designer-application": {
      "description": "Optional data & metadata not required to execute the protocol, used by the application that created this protocol",
      "type": "object",
      "properties": {
        "application-name": {
          "description": "Name of the application that created the protocol. Should be namespaced under the organization or individual who owns the organization, and be kebab-cased, eg \"opentrons/protocol-designer\"",
          "type": "string"
        },
        "application-version": {
          "description": "Version of the application that created the protocol",
          "type": "string"
        },
        "data": {
          "description": "Any data used by the application that created this protocol)",
          "type": "object"
        }
      }
    },

    "robot": {
      "required": ["model"],
      "properties": {
        "model": {
          "description": "Model of the robot this (currently only OT-2 Standard is supported)",
          "type": "string",
          "enum": ["OT-2 Standard"]
        }
      }
    },

    "pipettes": {
      "description": "The pipettes used in this protocol, keyed by an arbitrary unique ID",
      "additionalProperties": false,
      "$comment": "TODO: Ian 2018-11-06 next breaking change, drop 'model' and require 'name' field",
      "patternProperties": {
        ".+": {
          "description": "Fields describing an individual pipette",
          "type": "object",
          "required": ["mount", "model"],
          "properties": {
            "mount": {
              "description": "Where the pipette is mounted",
              "type": "string",
              "enum": ["left", "right"]
            },
            "name": {
              "$ref": "#/definitions/pipetteName"
            },
            "model": {
              "$ref": "#/definitions/pipette-model"
            }
          }
        }
      }
    },

    "labware": {
      "description": "The labware used in this protocol, keyed by an arbitrary unique ID",
      "patternProperties": {
        ".+": {
          "description": "Fields describing a single labware on the deck",
          "type": "object",
          "required": ["slot", "model"],
          "properties": {
            "slot": { "$ref": "#/definitions/slot" },
            "model": {
              "description": "Labware type, eg \"96-flat\". See http://docs.opentrons.com/containers.html for a full list of supported labware. TODO support custom labware in JSON",
              "type": "string"
            },

            "display-name": {
              "description": "An optional human-readable nickname for this labware. Eg \"Buffer Trough\"",
              "type": "string"
            }
          }
        }
      }
    },

    "procedure": {
      "description": "An array of \"subprocedure\" objects representing the steps to be executed on the robot",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["subprocedure"],
        "properties": {
          "annotation": {
            "description": "Optional info annotating the subprocedure",
            "type": "object",
            "required": ["name", "description"],
            "properties": {
              "name": {
                "type": ["string", "null"]
              },
              "description": {
                "type": ["string", "null"]
              }
            }
          },

          "subprocedure": {
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "description": "Aspirate / dispense / air gap commands",
                  "type": "object",
                  "required": ["command", "params"],
                  "additionalProperties": false,
                  "properties": {
                    "command": {
                      "enum": ["aspirate", "dispense", "air-gap"]
                    },
                    "params": {
                      "allOf": [
                        { "$ref": "#/definitions/flow-rate-params" },
                        { "$ref": "#/definitions/pipette-access-params" },
                        { "$ref": "#/definitions/volume-params" },
                        { "$ref": "#/definitions/offsetFromBottomMm" }
                      ]
                    }
                  }
                },

                {
                  "description": "Touch tip commands",
                  "type": "object",
                  "required": ["command", "params"],
                  "additionalProperties": false,
                  "properties": {
                    "command": {
                      "enum": ["touch-tip"]
                    },
                    "params": {
                      "allOf": [
                        { "$ref": "#/definitions/pipette-access-params" },
                        { "$ref": "#/definitions/offsetFromBottomMm" }
                      ]
                    }
                  }
                },

                {
                  "description": "Pick up tip / drop tip / blowout commands",
                  "type": "object",
                  "required": ["command", "params"],
                  "additionalProperties": false,
                  "properties": {
                    "command": {
                      "enum": ["pick-up-tip", "drop-tip", "blowout"]
                    },
                    "params": {
                      "allOf": [
                        { "$ref": "#/definitions/pipette-access-params" }
                      ]
                    }
                  }
                },

                {
                  "description": "Move to slot command. NOTE: this is an EXPERIMENTAL command, its behavior is subject to change in future releases.",
                  "type": "object",
                  "required": ["command", "params"],
                  "additionalProperties": false,
                  "properties": {
                    "command": { "enum": ["move-to-slot"] },
                    "params": {
                      "type": "object",
                      "required": ["pipette", "slot"],
                      "additionalProperties": false,
                      "properties": {
                        "pipette": { "type": "string" },
                        "slot": { "$ref": "#/definitions/slot" },
                        "offset": {
                          "description": "Optional offset from slot bottom left corner, in mm",
                          "type": "object",
                          "required": ["x", "y", "z"],
                          "properties": {
                            "x": { "type": "number" },
                            "y": { "type": "number" },
                            "z": { "type": "number" }
                          }
                        },
                        "minimum-z-height": {
                          "description": "Optional minimal Z margin in mm. If this is larger than the API's default safe Z margin, it will make the arc higher. If it's smaller, it will have no effect. Specifying this for movements that would not arc (moving within the same well in the same labware) will cause an arc movement instead. This param only supported in API v2, API v1 will ignore it.",
                          "type": "number",
                          "minimum": 0
                        },
                        "force-direct": {
                          "description": "Default is false. If true, moving from one labware/well to another will not arc to the default safe z, but instead will move directly to the specified location. This will also force the 'minimum-z-height' param to be ignored. In APIv1, this will use strategy='direct', which moves first in X/Y plane and then in Z. In API v2, a 'direct' movement is in X/Y/Z simultaneously",
                          "type": "boolean"
                        }
                      }
                    }
                  }
                },

                {
                  "description": "Delay command",
                  "type": "object",
                  "required": ["command", "params"],
                  "additionalProperties": false,
                  "properties": {
                    "command": {
                      "enum": ["delay"]
                    },
                    "params": {
                      "type": "object",
                      "additionalProperties": false,
                      "required": ["wait"],
                      "properties": {
                        "wait": {
                          "description": "either a number of seconds to wait (fractional values OK), or `true` to wait indefinitely until the user manually resumes the protocol",
                          "anyOf": [{ "type": "number" }, { "enum": [true] }]
                        },
                        "message": {
                          "description": "optional message describing the delay"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}

=== Opentrons/opentrons/protocol-designer/fixtures/protocol/1/example_1_1_0.json
{
  "protocol-schema": "1.0.0",
  "metadata": {
    "protocol-name": "Some name!",
    "author": "Author name",
    "description": "Description here",
    "created": 1560957631666,
    "category": null,
    "subcategory": null,
    "tags": []
  },
  "default-values": {
    "aspirate-flow-rate": {
      "p10_single": 5,
      "p10_multi": 5,
      "p50_single": 25,
      "p50_multi": 25,
      "p300_single": 150,
      "p300_multi": 150,
      "p1000_single": 500
    },
    "dispense-flow-rate": {
      "p10_single": 10,
      "p10_multi": 10,
      "p50_single": 50,
      "p50_multi": 50,
      "p300_single": 300,
      "p300_multi": 300,
      "p1000_single": 1000
    },
    "aspirate-mm-from-bottom": 1,
    "dispense-mm-from-bottom": 0.5,
    "touch-tip-mm-from-top": -1
  },
  "designer-application": {
    "application-name": "opentrons/protocol-designer",
    "application-version": "1.1.1",
    "applicationVersion": "1.1.1",
    "_internalAppBuildDate": "Wed, 03 Apr 2019 17:23:10 GMT",
    "data": {
      "pipetteTiprackAssignments": {
        "c6f45030-92a5-11e9-ac62-1b173f839d9e": "tiprack-10ul",
        "c6f47740-92a5-11e9-ac62-1b173f839d9e": "tiprack-200ul"
      },
      "dismissedWarnings": {
        "form": {},
        "timeline": {}
      },
      "ingredients": {
        "0": {
          "name": "samples",
          "description": null,
          "serialize": false,
          "liquidGroupId": "0"
        },
        "1": {
          "name": "dna",
          "description": null,
          "serialize": false,
          "liquidGroupId": "1"
        }
      },
      "ingredLocations": {
        "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well": {
          "A1": {
            "0": {
              "volume": 121
            }
          },
          "B1": {
            "0": {
              "volume": 121
            }
          },
          "C1": {
            "0": {
              "volume": 121
            }
          },
          "D1": {
            "0": {
              "volume": 121
            }
          },
          "E1": {
            "0": {
              "volume": 121
            }
          },
          "F1": {
            "1": {
              "volume": 44
            }
          },
          "G1": {
            "1": {
              "volume": 44
            }
          },
          "H1": {
            "1": {
              "volume": 44
            }
          }
        }
      },
      "savedStepForms": {
        "__INITIAL_DECK_SETUP_STEP__": {
          "stepType": "manualIntervention",
          "id": "__INITIAL_DECK_SETUP_STEP__",
          "labwareLocationUpdate": {
            "trashId": "12",
            "c6f4ec70-92a5-11e9-ac62-1b173f839d9e:tiprack-10ul": "1",
            "c6f51380-92a5-11e9-ac62-1b173f839d9e:tiprack-200ul": "2",
            "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well": "10"
          },
          "pipetteLocationUpdate": {
            "c6f45030-92a5-11e9-ac62-1b173f839d9e": "left",
            "c6f47740-92a5-11e9-ac62-1b173f839d9e": "right"
          }
        },
        "e7d36200-92a5-11e9-ac62-1b173f839d9e": {
          "id": "e7d36200-92a5-11e9-ac62-1b173f839d9e",
          "stepType": "moveLiquid",
          "stepName": "transfer things",
          "stepDetails": "yeah notes",
          "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
          "volume": "6",
          "changeTip": "always",
          "path": "single",
          "aspirate_wells_grouped": false,
          "aspirate_labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
          "aspirate_wells": ["A1"],
          "aspirate_wellOrder_first": "t2b",
          "aspirate_wellOrder_second": "l2r",
          "aspirate_mix_checkbox": true,
          "aspirate_mix_times": 3,
          "aspirate_mix_volume": "2",
          "aspirate_mmFromBottom": 1,
          "aspirate_touchTip_checkbox": true,
          "dispense_labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
          "dispense_wells": [
            "C6",
            "D6",
            "E6",
            "C7",
            "D7",
            "E7",
            "C8",
            "D8",
            "E8"
          ],
          "dispense_wellOrder_first": "b2t",
          "dispense_wellOrder_second": "r2l",
          "dispense_mix_checkbox": true,
          "dispense_mix_times": 2,
          "dispense_mix_volume": "3",
          "dispense_mmFromBottom": 2.5,
          "dispense_touchTip_checkbox": true,
          "disposalVolume_checkbox": true,
          "disposalVolume_volume": "1",
          "blowout_checkbox": true,
          "blowout_location": "trashId",
          "preWetTip": false,
          "aspirate_flowRate": 0.6,
          "aspirate_touchTip_mmFromBottom": 28.5
        },
        "18113c80-92a6-11e9-ac62-1b173f839d9e": {
          "id": "18113c80-92a6-11e9-ac62-1b173f839d9e",
          "stepType": "mix",
          "stepName": "mix",
          "stepDetails": "",
          "changeTip": "always",
          "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
          "mix_wellOrder_first": "t2b",
          "mix_wellOrder_second": "l2r",
          "blowout_checkbox": true,
          "blowout_location": "dest_well",
          "mix_mmFromBottom": 0.5,
          "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
          "volume": "5.5",
          "wells": ["F1"],
          "times": 3,
          "aspirate_flowRate": 8,
          "dispense_flowRate": 7,
          "mix_touchTip_checkbox": true,
          "mix_touchTip_mmFromBottom": 30.5
        },
        "2e622080-92a6-11e9-ac62-1b173f839d9e": {
          "id": "2e622080-92a6-11e9-ac62-1b173f839d9e",
          "stepType": "pause",
          "stepName": "pause",
          "stepDetails": "",
          "pauseForAmountOfTime": "true",
          "pauseHour": 1,
          "pauseMinute": 2,
          "pauseSecond": 3,
          "pauseMessage": "Delay plz"
        }
      },
      "orderedStepIds": [
        "e7d36200-92a5-11e9-ac62-1b173f839d9e",
        "18113c80-92a6-11e9-ac62-1b173f839d9e",
        "2e622080-92a6-11e9-ac62-1b173f839d9e"
      ]
    }
  },
  "robot": {
    "model": "OT-2 Standard"
  },
  "pipettes": {
    "c6f45030-92a5-11e9-ac62-1b173f839d9e": {
      "mount": "left",
      "model": "p10_single_v1.3",
      "name": "p10_single"
    },
    "c6f47740-92a5-11e9-ac62-1b173f839d9e": {
      "mount": "right",
      "model": "p50_single_v1.3",
      "name": "p50_single"
    }
  },
  "labware": {
    "trashId": {
      "slot": "12",
      "display-name": "Trash",
      "model": "fixed-trash"
    },
    "c6f4ec70-92a5-11e9-ac62-1b173f839d9e:tiprack-10ul": {
      "slot": "1",
      "display-name": "tiprack 10ul (1)",
      "model": "tiprack-10ul"
    },
    "c6f51380-92a5-11e9-ac62-1b173f839d9e:tiprack-200ul": {
      "slot": "2",
      "display-name": "tiprack 200ul (1)",
      "model": "tiprack-200ul"
    },
    "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well": {
      "slot": "10",
      "display-name": "96 deep well (1)",
      "model": "96-deep-well"
    }
  },
  "procedure": [
    {
      "annotation": {
        "name": "TODO Name 0",
        "description": "todo description"
      },
      "subprocedure": [
        {
          "command": "pick-up-tip",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "labware": "c6f4ec70-92a5-11e9-ac62-1b173f839d9e:tiprack-10ul",
            "well": "A1"
          }
        },
        {
          "command": "aspirate",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 1,
            "flow-rate": 0.6
          }
        },
        {
          "command": "dispense",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 2.5
          }
        },
        {
          "command": "aspirate",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 1,
            "flow-rate": 0.6
          }
        },
        {
          "command": "dispense",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 2.5
          }
        },
        {
          "command": "aspirate",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 1,
            "flow-rate": 0.6
          }
        },
        {
          "command": "dispense",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 2,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 2.5
          }
        },
        {
          "command": "aspirate",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "volume": 6,
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
            "well": "A1",
            "offsetFromBottomMm": 1,
            "flow-rate": 0.6
          }
        },
        {
          "command": "touch-tip",
          "params": {
            "pipette": "c6f45030-92a5-11e9-ac62-1b173f839d9e",
            "labware": "dafd4000-92a5-11e9-ac62-1b173f839d9e:96-deep-well",
