=== Opentrons/opentrons/shared-data/protocol/schemas/7.json
{
  "$id": "opentronsProtocolSchemaV7",
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "pipetteName": {
      "description": "Name of a pipette. Does not contain info about specific model/version. Should match keys in pipetteNameSpecs.json file",
      "type": "string",
      "enum": [
        "p10_single",
        "p10_multi",
        "p20_single_gen2",
        "p20_multi_gen2",
        "p50_single",
        "p50_multi",
        "p300_single",
        "p300_multi",
        "p300_single_gen2",
        "p300_multi_gen2",
        "p1000_single",
        "p1000_single_gen2",
        "p50_single_gen3",
        "p50_multi_gen3",
        "p1000_single_gen3",
        "p1000_multi_gen3",
        "p1000_96"
      ]
    },

    "moduleOnlyParams": {
      "required": ["moduleId"],
      "additionalProperties": false,
      "properties": {
        "moduleId": {
          "type": "string",
          "description": "Unique identifier of module to target. Must be a key from the top level 'modules' object"
        }
      }
    },

    "offset": {
      "description": "x, y, and z component of offset vector in mm",
      "properties": {
        "x": { "type": "number" },
        "y": { "type": "number" },
        "z": { "type": "number" }
      }
    },

    "pipetteAccessParams": {
      "required": ["pipetteId", "labwareId", "wellName"],
      "properties": {
        "pipetteId": {
          "type": "string"
        },
        "labwareId": {
          "type": "string"
        },
        "wellName": {
          "type": "string"
        }
      }
    },

    "volumeParams": {
      "required": ["volume"],
      "volume": {
        "type": "number"
      }
    },

    "flowRate": {
      "required": ["flowRate"],
      "properties": {
        "flowRate": {
          "description": "flow rate in ul/sec",
          "type": "number",
          "exclusiveMinimum": 0
        }
      }
    },

    "wellLocation": {
      "properties": {
        "origin": {
          "type": "string",
          "description": "reference location with respect to a well from which to apply an offset if given (e.g. 'bottom' || 'top')"
        },
        "offset": {
          "$ref": "#/definitions/offset",
          "description": "X, Y, Z offset from the specified origin with respect to well"
        }
      }
    },

    "labwareLocation": {
      "oneOf": [
        {
          "required": ["slotName"],
          "properties": {
            "slotName": {
              "description": "Unique string identifier that corresponds to a slot in the referenced deck definition's locations",
              "type": "string"
            }
          }
        },
        {
          "required": ["moduleId"],
          "properties": {
            "moduleId": {
              "description": "Unique identifier of destination module. Must be a key from the top level 'modules' object.",
              "type": "string"
            }
          }
        },
        {
          "const": "offDeck",
          "description": "String literal 'offDeck'. Used to load a labware without placing it on the deck"
        }
      ]
    }
  },

  "type": "object",
  "additionalProperties": false,
  "required": [
    "$otSharedSchema",
    "schemaVersion",
    "metadata",
    "robot",
    "labwareDefinitions",
    "commands"
  ],
  "properties": {
    "$otSharedSchema": {
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension.",
      "enum": ["#/protocol/schemas/7"]
    },

    "schemaVersion": {
      "description": "Schema version of a protocol is a single integer",
      "enum": [7]
    },

    "metadata": {
      "description": "Optional metadata about the protocol",
      "type": "object",

      "properties": {
        "protocolName": {
          "description": "A short, human-readable name for the protocol",
          "type": "string"
        },
        "author": {
          "description": "The author or organization who created the protocol",
          "type": "string"
        },
        "description": {
          "description": "A text description of the protocol.",
          "type": ["string", "null"]
        },

        "created": {
          "description": "UNIX timestamp when this file was created",
          "type": "number"
        },
        "lastModified": {
          "description": "UNIX timestamp when this file was last modified",
          "type": ["number", "null"]
        },

        "category": {
          "description": "Category of protocol (eg, \"Basic Pipetting\")",
          "type": ["string", "null"]
        },
        "subcategory": {
          "description": "Subcategory of protocol (eg, \"Cell Plating\")",
          "type": ["string", "null"]
        },
        "tags": {
          "description": "Tags to be used in searching for this protocol",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },

    "designerApplication": {
      "description": "Optional data & metadata not required to execute the protocol, used by the application that created this protocol",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the application that created the protocol. Should be namespaced under the organization or individual who owns the organization, eg \"opentrons/protocol-designer\"",
          "type": "string"
        },
        "version": {
          "description": "Version of the application that created the protocol",
          "type": "string"
        },
        "data": {
          "description": "Any data used by the application that created this protocol",
          "type": "object"
        }
      }
    },

    "robot": {
      "required": ["model", "deckId"],
      "properties": {
        "model": {
          "description": "Model of the robot this protocol is written for",
          "type": "string",
          "enum": ["OT-2 Standard", "OT-3 Standard"]
        },
        "deckId": {
          "description": "Identifier of physical deck this protocol is written for. This should match a top-level key in shared-data/deck/definitions/3.json",
          "type": "string"
        }
      }
    },

    "pipettes": {
      "description": "The pipettes used in this protocol, keyed by a unique identifier (pipetteId)",
      "additionalProperties": false,
      "patternProperties": {
        ".+": {
          "description": "Fields describing an individual pipette",
          "type": "object",
          "required": ["name"],
          "additionalProperties": false,
          "properties": {
            "name": {
              "$ref": "#/definitions/pipetteName"
            }
          }
        }
      }
    },

    "labwareDefinitions": {
      "description": "All labware definitions used by labware in this protocol, keyed by a unique identifier (definitionId)",
      "patternProperties": {
        ".+": {
          "$ref": "opentronsLabwareSchemaV2"
        }
      }
    },

    "labware": {
      "description": "All instances of labware used in this protocol, and references to their definitions' labwareId, keyed by a unique identifier (labwareId)",
      "patternProperties": {
        ".+": {
          "description": "Fields describing a single labware",
          "type": "object",
          "required": ["definitionId"],
          "additionalProperties": false,
          "properties": {
            "definitionId": {
              "description": "reference to this labware's ID in \"labwareDefinitions\"",
              "type": "string"
            },
            "displayName": {
              "description": "An optional human-readable nickname for this labware instance within this protocol. Eg \"Buffer Trough\"",
              "type": "string"
            }
          }
        }
      }
    },

    "liquids": {
      "description": "All instances of liquid used in this protocol, keyed by a unique identifier (liquidId)",
      "patternProperties": {
        ".+": {
          "description": "Fields describing a single liquid",
          "type": "object",
          "required": ["displayName", "description"],
          "properties": {
            "displayName": {
              "description": "An human-readable name for this liquid.",
              "type": "string"
            },
            "description": {
              "description": "A description of this liquid.",
              "type": "string"
            },
            "displayColor": {
              "description": "Hex color code, with hash included, to represent the specified liquid. Standard three-value, four-value, six-value, and eight-value syntax are all acceptable.",
              "type": "string"
            }
          }
        }
      }
    },

    "modules": {
      "description": "All modules used in this protocol keyed by a unique identifier (moduleId)",
      "patternProperties": {
        ".+": {
          "description": "Fields describing a single module on the deck",
          "type": "object",
          "required": ["model"],
          "additionalProperties": false,
          "properties": {
            "model": {
              "description": "model of module. Eg 'magneticModuleV1' or 'magneticModuleV2'. This should match a top-level key in shared-data/module/definitions/2.json",
              "type": "string"
            }
          }
        }
      }
    },

    "commands": {
      "description": "An array of command objects representing steps to be executed on the robot.",
      "type": "array",
      "items": { "$ref": "opentronsCommandSchemaV7" }
    },

    "commandAnnotations": {
      "type": "array",
      "items": {
        "description": "An optional object of annotations associated with commands.",
        "type": "object",
        "required": ["commandIds", "annotationType"],
        "properties": {
          "commandIds": {
            "description": "An array of command ids that correspond to the targeted grouping of this annotation",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "annotationType": {
            "description": "The type of annotation (e.g. 'transfer', 'initialSetup')",
            "type": "string"
          },
          "params": {
            "description": "The parameters used to create this grouping of atomic commands",
            "type": "object"
          }
        }
      }
    }
  }
}

=== Opentrons/opentrons/protocol-designer/fixtures/protocol/7/doitAllV3MigratedToV7.json
{
  "metadata": {
    "protocolName": "Do it all v3",
    "author": "Fixture",
    "description": "Test all v3 commands",
    "created": 1585930833548,
    "lastModified": 1688596597598,
    "category": null,
    "subcategory": null,
    "tags": []
  },
  "designerApplication": {
    "name": "opentrons/protocol-designer",
    "version": "7.0.0",
    "data": {
      "_internalAppBuildDate": "Wed, 05 Jul 2023 20:42:07 GMT",
      "defaultValues": {
        "aspirate_mmFromBottom": 1,
        "dispense_mmFromBottom": 0.5,
        "touchTip_mmFromTop": -1,
        "blowout_mmFromTop": 0
      },
      "pipetteTiprackAssignments": {
        "0b3f2210-75c7-11ea-b42f-4b64e50f43e5": "opentrons/opentrons_96_tiprack_300ul/1"
      },
      "dismissedWarnings": { "form": {}, "timeline": {} },
      "ingredients": {
        "0": {
          "name": "Water",
          "description": null,
          "serialize": false,
          "liquidGroupId": "0"
        }
      },
      "ingredLocations": {
        "1e610d40-75c7-11ea-b42f-4b64e50f43e5:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1": {
          "A1": { "0": { "volume": 100 } },
          "B1": { "0": { "volume": 100 } },
          "C1": { "0": { "volume": 100 } },
          "D1": { "0": { "volume": 100 } },
          "E1": { "0": { "volume": 100 } },
          "F1": { "0": { "volume": 100 } },
          "G1": { "0": { "volume": 100 } },
          "H1": { "0": { "volume": 100 } },
          "A2": { "0": { "volume": 100 } },
          "B2": { "0": { "volume": 100 } },
          "C2": { "0": { "volume": 100 } },
          "D2": { "0": { "volume": 100 } },
          "E2": { "0": { "volume": 100 } },
          "F2": { "0": { "volume": 100 } },
          "G2": { "0": { "volume": 100 } },
          "H2": { "0": { "volume": 100 } }
        }
      },
      "savedStepForms": {
        "__INITIAL_DECK_SETUP_STEP__": {
          "labwareLocationUpdate": {
            "fixedTrash": "12",
            "0b44c760-75c7-11ea-b42f-4b64e50f43e5:opentrons/opentrons_96_tiprack_300ul/1": "2",
            "1e610d40-75c7-11ea-b42f-4b64e50f43e5:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1": "1",
            "21ed8f60-75c7-11ea-b42f-4b64e50f43e5:opentrons/opentrons_24_aluminumblock_generic_2ml_screwcap/1": "3"
          },
          "pipetteLocationUpdate": {
            "0b3f2210-75c7-11ea-b42f-4b64e50f43e5": "left"
          },
          "moduleLocationUpdate": {},
          "stepType": "manualIntervention",
          "id": "__INITIAL_DECK_SETUP_STEP__"
        },
        "3961e4c0-75c7-11ea-b42f-4b64e50f43e5": {
          "pipette": "0b3f2210-75c7-11ea-b42f-4b64e50f43e5",
          "volume": "40",
          "changeTip": "always",
          "path": "multiDispense",
          "aspirate_wells_grouped": false,
          "aspirate_flowRate": null,
          "aspirate_labware": "1e610d40-75c7-11ea-b42f-4b64e50f43e5:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1",
          "aspirate_wells": ["A1"],
          "aspirate_wellOrder_first": "t2b",
          "aspirate_wellOrder_second": "l2r",
          "aspirate_mix_checkbox": true,
          "aspirate_mix_times": "2",
          "aspirate_mix_volume": "30",
          "aspirate_mmFromBottom": 1,
          "aspirate_touchTip_checkbox": true,
          "aspirate_touchTip_mmFromBottom": 12.8,
          "dispense_flowRate": null,
          "dispense_labware": "21ed8f60-75c7-11ea-b42f-4b64e50f43e5:opentrons/opentrons_24_aluminumblock_generic_2ml_screwcap/1",
          "dispense_wells": ["A1", "A2"],
          "dispense_wellOrder_first": "t2b",
          "dispense_wellOrder_second": "l2r",
          "dispense_mix_checkbox": false,
          "dispense_mix_times": null,
          "dispense_mix_volume": null,
          "dispense_mmFromBottom": 0.5,
          "dispense_touchTip_checkbox": true,
          "dispense_touchTip_mmFromBottom": 40,
          "disposalVolume_checkbox": true,
          "disposalVolume_volume": "20",
          "blowout_checkbox": false,
          "blowout_location": "fixedTrash",
          "preWetTip": false,
          "aspirate_airGap_checkbox": false,
          "aspirate_airGap_volume": null,
          "aspirate_delay_checkbox": false,
          "aspirate_delay_mmFromBottom": "1",
          "aspirate_delay_seconds": "1",
          "dispense_airGap_checkbox": false,
          "dispense_airGap_volume": null,
          "dispense_delay_checkbox": false,
          "dispense_delay_seconds": "1",
          "dispense_delay_mmFromBottom": "0.5",
          "id": "3961e4c0-75c7-11ea-b42f-4b64e50f43e5",
          "stepType": "moveLiquid",
          "stepName": "transfer",
          "stepDetails": ""
        },
        "54dc3200-75c7-11ea-b42f-4b64e50f43e5": {
          "pauseAction": "untilResume",
          "pauseHour": null,
          "pauseMinute": null,
          "pauseSecond": null,
          "pauseMessage": "Wait until user intervention",
          "moduleId": null,
          "pauseTemperature": null,
          "id": "54dc3200-75c7-11ea-b42f-4b64e50f43e5",
          "stepType": "pause",
          "stepName": "pause",
          "stepDetails": ""
        },
        "5db07ad0-75c7-11ea-b42f-4b64e50f43e5": {
          "pauseAction": "untilTime",
          "pauseHour": null,
          "pauseMinute": "1",
          "pauseSecond": "2",
          "pauseMessage": "",
          "moduleId": null,
          "pauseTemperature": null,
          "id": "5db07ad0-75c7-11ea-b42f-4b64e50f43e5",
          "stepType": "pause",
          "stepName": "pause",
          "stepDetails": ""
        },
        "a4cee9a0-75dc-11ea-b42f-4b64e50f43e5": {
          "times": "3",
          "changeTip": "always",
          "labware": "1e610d40-75c7-11ea-b42f-4b64e50f43e5:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1",
          "mix_wellOrder_first": "t2b",
          "mix_wellOrder_second": "l2r",
          "blowout_checkbox": true,
          "blowout_location": "fixedTrash",
          "mix_mmFromBottom": 0.5,
          "pipette": "0b3f2210-75c7-11ea-b42f-4b64e50f43e5",
          "volume": "35",
          "wells": ["D2", "E2"],
          "aspirate_flowRate": 40,
          "dispense_flowRate": 35,
          "aspirate_delay_checkbox": false,
          "aspirate_delay_seconds": "1",
          "dispense_delay_checkbox": false,
          "dispense_delay_seconds": "1",
          "mix_touchTip_checkbox": true,
          "mix_touchTip_mmFromBottom": 11.8,
          "id": "a4cee9a0-75dc-11ea-b42f-4b64e50f43e5",
          "stepType": "mix",
          "stepName": "mix",
          "stepDetails": ""
        }
      },
      "orderedStepIds": [
        "5db07ad0-75c7-11ea-b42f-4b64e50f43e5",
        "3961e4c0-75c7-11ea-b42f-4b64e50f43e5",
        "54dc3200-75c7-11ea-b42f-4b64e50f43e5",
        "a4cee9a0-75dc-11ea-b42f-4b64e50f43e5"
      ]
    }
  },
  "robot": { "model": "OT-2 Standard", "deckId": "ot2_standard" },
  "pipettes": {
    "0b3f2210-75c7-11ea-b42f-4b64e50f43e5": { "name": "p300_single_gen2" }
  },
  "labware": {
    "fixedTrash": {
      "displayName": "Trash",
      "definitionId": "opentrons/opentrons_1_trash_1100ml_fixed/1"
    },
    "0b44c760-75c7-11ea-b42f-4b64e50f43e5:opentrons/opentrons_96_tiprack_300ul/1": {
      "displayName": "Opentrons 96 Tip Rack 300 µL",
      "definitionId": "opentrons/opentrons_96_tiprack_300ul/1"
    },
    "1e610d40-75c7-11ea-b42f-4b64e50f43e5:opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1": {
      "displayName": "NEST 96 Well Plate 100 µL PCR Full Skirt",
      "definitionId": "opentrons/nest_96_wellplate_100ul_pcr_full_skirt/1"
    },
    "21ed8f60-75c7-11ea-b42f-4b64e50f43e5:opentrons/opentrons_24_aluminumblock_generic_2ml_screwcap/1": {
      "displayName": "Opentrons 24 Well Aluminum Block with Generic 2 mL Screwcap",
      "definitionId": "opentrons/opentrons_24_aluminumblock_generic_2ml_screwcap/1"
    }
  },
  "liquids": {
    "0": {
      "displayName": "Water",
      "description": "",
      "displayColor": "#b925ff"
    }
  },
  "labwareDefinitions": {
    "opentrons/opentrons_96_tiprack_300ul/1": {
      "ordering": [
        ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"],
        ["A2", "B2", "C2", "D2", "E2", "F2", "G2", "H2"],
        ["A3", "B3", "C3", "D3", "E3", "F3", "G3", "H3"],
        ["A4", "B4", "C4", "D4", "E4", "F4", "G4", "H4"],
        ["A5", "B5", "C5", "D5", "E5", "F5", "G5", "H5"],
        ["A6", "B6", "C6", "D6", "E6", "F6", "G6", "H6"],
        ["A7", "B7", "C7", "D7", "E7", "F7", "G7", "H7"],
        ["A8", "B8", "C8", "D8", "E8", "F8", "G8", "H8"],
        ["A9", "B9", "C9", "D9", "E9", "F9", "G9", "H9"],
        ["A10", "B10", "C10", "D10", "E10", "F10", "G10", "H10"],
        ["A11", "B11", "C11", "D11", "E11", "F11", "G11", "H11"],
        ["A12", "B12", "C12", "D12", "E12", "F12", "G12", "H12"]
      ],
      "brand": {
        "brand": "Opentrons",
        "brandId": [],
        "links": [
          "https://shop.opentrons.com/collections/opentrons-tips/products/opentrons-300ul-tips"
        ]
      },
      "metadata": {
        "displayName": "Opentrons 96 Tip Rack 300 µL",
        "displayCategory": "tipRack",
        "displayVolumeUnits": "µL",
        "tags": []
      },
      "dimensions": {
        "xDimension": 127.76,
        "yDimension": 85.48,
        "zDimension": 64.49
      },
      "wells": {
        "A1": {
          "depth": 59.3,
          "shape": "circular",
          "diameter": 5.23,
          "totalLiquidVolume": 300,
          "x": 14.38,
          "y": 74.24,
          "z": 5.39
        },
        "B1": {
          "depth": 59.3,
          "shape": "circular",
          "diameter": 5.23,
          "totalLiquidVolume": 300,
          "x": 14.38,
          "y": 65.24,
          "z": 5.39
        },
        "C1": {
          "depth": 59.3,
          "shape": "circular",
          "diameter": 5.23,
          "totalLiquidVolume": 300,
          "x": 14.38,
          "y": 56.24,
          "z": 5.39
        },
        "D1": {
          "depth": 59.3,
