=== Opentrons/opentrons/shared-data/pipette/schemas/2/pipetteLiquidPropertiesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "positiveNumber": {
      "type": "number",
      "minimum": 0
    },
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "liquidHandlingSpecs": {
      "description": "Object containing linear equations for translating between uL of liquid and mm of plunger travel. There is one linear equation for aspiration and one for dispense",
      "type": "object",
      "required": ["aspirate", "dispense"],
      "additionalProperties": false,
      "properties": {
        "aspirate": { "$ref": "#/definitions/xyzArray" },
        "dispense": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "flowRate": {
      "description": "Object with a default value and optional dict keyed by api level. If API level is unavailable, default is used.",
      "type": "object",
      "required": ["default", "valuesByApiLevel"],
      "properties": {
        "default": {
          "$ref": "#/definitions/positiveNumber",
          "$comment": "The default value of the flowrate"
        },
        "valuesByApiLevel": { "type": "object", "required": [] }
      }
    }
  },
  "type": "object",
  "required": [
    "$otSharedSchema",
    "maxVolume",
    "minVolume",
    "defaultTipracks",
    "supportedTips"
  ],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteLiquidPropertiesSchema.json is a reference to this schema."
    },
    "supportedTips": {
      "type": "object",
      "description": "A container of supported tip types",
      "properties": {
        "patternProperties": {
          "description": "Tip specific liquid handling properties for a given pipette. Using the active tip on a pipette, we will look up the pipetting configurations associated with that tip+pipette combo.",
          "type": "object",
          "$comment": "Example key: 't50'",
          "^t[0-9]{2,4}": {
            "required": [
              "defaultAspirateFlowRate",
              "defaultDispenseFlowRate",
              "defaultBlowOutFlowRate",
              "aspirate",
              "dispense"
            ],
            "properties": {
              "defaultAspirateFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultDispenseFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultBlowOutFlowRate": {
                "$ref": "#/definitions/flowRate",
                "$comment": "for lowVolumeDefault only, the flowRate matches the uiMaxFlowRate. This does not change physical behavior and was made for UI purposes"
              },
              "defaultFlowAcceleration": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultTipLength": {
                "$ref": "#/definitions/positiveNumber"
              },
              "defaultReturnTipHeight": {
                "$ref": "#/definitions/positiveNumber"
              },
              "aspirate": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "dispense": {
                "type": "array",
                "items": { "$ref": "#/definitions/liquidHandlingSpecs" }
              },
              "uiMaxFlowRate": {
                "$ref": "#/definitions/positiveNumber",
                "$comment": "To be used in frontend applications only since it is the limit-to-lowest-max",
                "description": "An optional number to represent each pipette's supported tip max flow rate for aspirate and dispense. The limit is the lowest max flow rate given all the tip's volumes minus 2% for safety."
              }
            }
          }
        }
      }
    },
    "maxVolume": { "$ref": "#/definitions/positiveNumber" },
    "minVolume": { "$ref": "#/definitions/positiveNumber" },
    "defaultTipracks": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/eight_channel/p10/default/1_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t10": {
      "defaultAspirateFlowRate": {
        "default": 5,
        "valuesByApiLevel": { "2.0": 5 }
      },
      "defaultDispenseFlowRate": {
        "default": 10,
        "valuesByApiLevel": { "2.0": 10 }
      },
      "defaultBlowOutFlowRate": {
        "default": 1000,
        "valuesByApiLevel": { "2.0": 1000 }
      },
      "defaultTipLength": 33.0,
      "aspirate": {
        "default": {
          "1": [
            [0.8649, 0.0374, 0.8484],
            [1.2416, -0.0987, 0.9503],
            [1.6053, -0.069, 0.9134],
            [1.9851, -0.0226, 0.839],
            [2.3481, -0.0313, 0.8561],
            [2.7207, -0.0143, 0.8164],
            [3.0702, -0.028, 0.8536],
            [4.5998, -0.0006, 0.7694],
            [6.1063, -0.0022, 0.7769],
            [7.6504, 0.0011, 0.7564],
            [9.1863, 0.0003, 0.7626],
            [10.7574, 0.0018, 0.7488],
            [12.2984, -0.4986, 6.1321]
          ]
        }
      },
      "dispense": { "default": { "1": [[12.74444519, 0.0, 0.8058688085]] } },
      "defaultPushOutVolume": 0
    }
  },
  "maxVolume": 10,
  "minVolume": 1.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_10ul/1",
    "opentrons/opentrons_96_filtertiprack_10ul/1",
    "opentrons/geb_96_tiprack_10ul/1"
  ]
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/3_4.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t50": {
      "uiMaxFlowRate": 762.1,
      "defaultAspirateFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultDispenseFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultBlowOutFlowRate": {
        "default": 478,
        "valuesByApiLevel": { "2.14": 478 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.0671, 16.2577, -0.617],
            [0.36, 6.1069, 0.0646],
            [0.7471, 4.962, 0.4767],
            [1.1486, 3.7975, 1.3468],
            [1.5557, 2.86, 2.4236],
            [1.9671, 2.1173, 3.5789],
            [2.4, 1.4901, 4.8128],
            [2.8571, 1.1013, 5.746],
            [3.0371, -2.7328, 16.7006],
            [4.2257, 1.6852, 3.2826],
            [5.1343, 0.9119, 6.5502],
            [5.9643, 0.4559, 8.8912],
            [6.9471, 0.4195, 9.1086],
            [7.9814, 0.2568, 10.2388],
            [9.15, 0.2013, 10.6818],
            [10.4614, 0.1648, 11.0153],
            [11.91, 0.1068, 11.6225],
            [13.5886, 0.1165, 11.507],
            [15.4914, 0.0933, 11.8218],
            [17.5329, 0.0427, 12.6065],
            [19.9186, 0.0575, 12.3467],
            [22.6129, 0.0486, 12.5247],
            [25.6157, 0.033, 12.8773],
            [29.0243, 0.0314, 12.9164],
            [32.8643, 0.0256, 13.0874],
            [37.1857, 0.0202, 13.2621],
            [41.99, 0.0124, 13.5525],
            [47.4957, 0.0149, 13.4474],
            [53.6686, 0.0113, 13.6208]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.0671, 16.2577, -0.617],
            [0.36, 6.1069, 0.0646],
            [0.7471, 4.962, 0.4767],
            [1.1486, 3.7975, 1.3468],
            [1.5557, 2.86, 2.4236],
            [1.9671, 2.1173, 3.5789],
            [2.4, 1.4901, 4.8128],
            [2.8571, 1.1013, 5.746],
            [3.0371, -2.7328, 16.7006],
            [4.2257, 1.6852, 3.2826],
            [5.1343, 0.9119, 6.5502],
            [5.9643, 0.4559, 8.8912],
            [6.9471, 0.4195, 9.1086],
            [7.9814, 0.2568, 10.2388],
            [9.15, 0.2013, 10.6818],
            [10.4614, 0.1648, 11.0153],
            [11.91, 0.1068, 11.6225],
            [13.5886, 0.1165, 11.507],
            [15.4914, 0.0933, 11.8218],
            [17.5329, 0.0427, 12.6065],
            [19.9186, 0.0575, 12.3467],
            [22.6129, 0.0486, 12.5247],
            [25.6157, 0.033, 12.8773],
            [29.0243, 0.0314, 12.9164],
            [32.8643, 0.0256, 13.0874],
            [37.1857, 0.0202, 13.2621],
            [41.99, 0.0124, 13.5525],
            [47.4957, 0.0149, 13.4474],
            [53.6686, 0.0113, 13.6208]
          ]
        }
      },
      "defaultPushOutVolume": 7
    },
    "t200": {
      "uiMaxFlowRate": 745,
      "defaultAspirateFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultDispenseFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultBlowOutFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 58.35,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.1983, -15.5377, 4.4239],
            [0.2467, 1.5308, 1.0387],
            [0.285, -0.563, 1.5551],
            [1.395, 3.9759, 0.2615],
            [2.22, 2.4705, 2.3617],
            [3.01, 1.5233, 4.4644],
            [3.975, 1.1548, 5.5735],
            [4.99, 0.6825, 7.4508],
            [6.2033, 0.5072, 8.326],
            [7.6183, 0.3622, 9.2251],
            [9.3183, 0.2822, 9.8345],
            [11.305, 0.1951, 10.6468],
            [13.575, 0.1202, 11.4935],
            [16.2267, 0.0827, 12.0016],
            [19.4583, 0.0802, 12.0431],
            [23.33, 0.0692, 12.2572],
            [27.765, 0.0373, 13.0009],
            [33.1483, 0.0402, 12.9213],
            [39.3683, 0.0227, 13.5002],
            [46.82, 0.022, 13.5259],
            [55.5967, 0.0159, 13.8114],
            [65.8433, 0.0103, 14.1256],
            [77.925, 0.0078, 14.2893],
            [92.1383, 0.0057, 14.4522],
            [108.7467, 0.0033, 14.6725],
            [128.425, 0.0033, 14.6798],
            [151.605, 0.0025, 14.7791],
            [178.705, 0.0013, 14.953],
            [210.66, 0.0012, 14.9867]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.1983, -15.5377, 4.4239],
            [0.2467, 1.5308, 1.0387],
            [0.285, -0.563, 1.5551],
            [1.395, 3.9759, 0.2615],
            [2.22, 2.4705, 2.3617],
            [3.01, 1.5233, 4.4644],
            [3.975, 1.1548, 5.5735],
            [4.99, 0.6825, 7.4508],
            [6.2033, 0.5072, 8.326],
            [7.6183, 0.3622, 9.2251],
            [9.3183, 0.2822, 9.8345],
            [11.305, 0.1951, 10.6468],
            [13.575, 0.1202, 11.4935],
            [16.2267, 0.0827, 12.0016],
            [19.4583, 0.0802, 12.0431],
            [23.33, 0.0692, 12.2572],
            [27.765, 0.0373, 13.0009],
            [33.1483, 0.0402, 12.9213],
            [39.3683, 0.0227, 13.5002],
            [46.82, 0.022, 13.5259],
            [55.5967, 0.0159, 13.8114],
            [65.8433, 0.0103, 14.1256],
            [77.925, 0.0078, 14.2893],
            [92.1383, 0.0057, 14.4522],
            [108.7467, 0.0033, 14.6725],
            [128.425, 0.0033, 14.6798],
            [151.605, 0.0025, 14.7791],
            [178.705, 0.0013, 14.953],
            [210.66, 0.0012, 14.9867]
          ]
        }
      },
      "defaultPushOutVolume": 5
    },
    "t1000": {
      "uiMaxFlowRate": 763.3,
      "defaultAspirateFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultDispenseFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultBlowOutFlowRate": {
        "default": 716,
        "valuesByApiLevel": { "2.14": 716 }
      },
      "defaultFlowAcceleration": 24000.0,
      "defaultTipLength": 95.6,
      "defaultReturnTipHeight": 0.82,
      "aspirate": {
        "default": {
          "1": [
            [4.1286, 0.3769, 9.3332],
            [5.0986, 0.2729, 9.7625],
            [6.3586, 0.2994, 9.6274],
            [7.7614, 0.1049, 10.8643],
            [9.7671, 0.2566, 9.6866],
            [12.0071, 0.1033, 11.1837],
            [14.8286, 0.1073, 11.1358],
            [18.2071, 0.0695, 11.6974],
            [22.4171, 0.0646, 11.7851],
            [27.63, 0.0566, 11.9646],
            [33.8729, 0.0359, 12.5378],
            [41.4414, 0.0266, 12.8514],
            [50.7643, 0.0238, 12.9692],
            [61.9014, 0.0144, 13.4483],
            [75.2757, 0.0091, 13.7703],
            [91.67, 0.0088, 13.7987],
            [111.55, 0.0068, 13.981],
            [135.6043, 0.005, 14.1829],
            [164.4186, 0.0029, 14.468],
            [199.5471, 0.0028, 14.4843],
            [242.0229, 0.0021, 14.6227],
            [293.0014, 0.0012, 14.8373],
            [354.6614, 0.001, 14.9068],
            [428.7743, 0.0005, 15.0531],
            [518.0643, 0.0003, 15.1363],
            [626.0157, 0.0003, 15.16],
            [755.8643, 0.0002, 15.2487],
            [912.3771, 0.0001, 15.2914],
            [1101.4771, 0.0001, 15.2962]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [4.1286, 0.3769, 9.3332],
            [5.0986, 0.2729, 9.7625],
            [6.3586, 0.2994, 9.6274],
            [7.7614, 0.1049, 10.8643],
            [9.7671, 0.2566, 9.6866],
            [12.0071, 0.1033, 11.1837],
            [14.8286, 0.1073, 11.1358],
            [18.2071, 0.0695, 11.6974],
            [22.4171, 0.0646, 11.7851],
            [27.63, 0.0566, 11.9646],
            [33.8729, 0.0359, 12.5378],
            [41.4414, 0.0266, 12.8514],
            [50.7643, 0.0238, 12.9692],
            [61.9014, 0.0144, 13.4483],
            [75.2757, 0.0091, 13.7703],
            [91.67, 0.0088, 13.7987],
            [111.55, 0.0068, 13.981],
            [135.6043, 0.005, 14.1829],
            [164.4186, 0.0029, 14.468],
            [199.5471, 0.0028, 14.4843],
            [242.0229, 0.0021, 14.6227],
            [293.0014, 0.0012, 14.8373],
            [354.6614, 0.001, 14.9068],
            [428.7743, 0.0005, 15.0531],
            [518.0643, 0.0003, 15.1363],
            [626.0157, 0.0003, 15.16],
            [755.8643, 0.0002, 15.2487],
            [912.3771, 0.0001, 15.2914],
            [1101.4771, 0.0001, 15.2962]
          ]
        }
      },
      "defaultPushOutVolume": 20
    }
  },
  "maxVolume": 1000,
  "minVolume": 5,
  "defaultTipracks": [
    "opentrons/opentrons_flex_96_tiprack_1000ul/1",
    "opentrons/opentrons_flex_96_tiprack_200ul/1",
    "opentrons/opentrons_flex_96_tiprack_50ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_1000ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_200ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
  ]
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/single_channel/p1000/default/2_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t1000": {
      "defaultAspirateFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultDispenseFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultBlowOutFlowRate": {
        "default": 274.7,
        "valuesByApiLevel": { "2.0": 137.35, "2.6": 274.7 }
      },
      "defaultTipLength": 78.3,
      "defaultReturnTipHeight": 0.83,
      "aspirate": {
        "default": {
          "1": [
            [83.6, 0.01502, 25.62],
            [90.39, 0.0152, 24.45],
            [104.1, 0.01386, 24.57],
            [117.7, 0.00991, 24.98],
            [131.3, 0.007542, 25.26],
            [158.6, 0.006723, 25.37],
            [186.1, 0.005602, 25.55],
            [199.9, 0.005013, 25.66],
            [213.6, 0.002767, 26.11],
            [241.2, 0.003594, 25.93],
            [268.6, 0.002371, 26.22],
            [323.5, 0.001687, 26.41],
            [378.3, 0.001273, 26.54],
            [433.3, 0.001039, 26.63],
            [460.8, 0.0007889, 26.74],
            [488.1, 0.0004039, 26.92],
            [515.5, 0.0005667, 26.84],
            [542.9, 0.0005983, 26.82],
            [570.4, 0.0006121, 26.81],
            [597.7, 0.0002485, 27.02],
            [625.4, 0.0008384, 26.67],
            [652.5, -0.0001662, 27.3],
            [707.4, 0.0003177, 26.98],
            [762.4, 0.000383, 26.94],
            [817.1, 0.0001665, 27.1],
            [872.1, 0.000301, 26.99],
            [927.0, 0.0002205, 27.06],
            [981.8, 0.0001571, 27.12],
            [1010.0, 0.0003381, 26.94]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [83.6, 0.01502, 25.62],
            [90.39, 0.0152, 24.45],
            [104.1, 0.01386, 24.57],
            [117.7, 0.00991, 24.98],
            [131.3, 0.007542, 25.26],
            [158.6, 0.006723, 25.37],
            [186.1, 0.005602, 25.55],
            [199.9, 0.005013, 25.66],
            [213.6, 0.002767, 26.11],
            [241.2, 0.003594, 25.93],
            [268.6, 0.002371, 26.22],
            [323.5, 0.001687, 26.41],
            [378.3, 0.001273, 26.54],
            [433.3, 0.001039, 26.63],
            [460.8, 0.0007889, 26.74],
            [488.1, 0.0004039, 26.92],
            [515.5, 0.0005667, 26.84],
            [542.9, 0.0005983, 26.82],
            [570.4, 0.0006121, 26.81],
            [597.7, 0.0002485, 27.02],
            [625.4, 0.0008384, 26.67],
            [652.5, -0.0001662, 27.3],
            [707.4, 0.0003177, 26.98],
            [762.4, 0.000383, 26.94],
            [817.1, 0.0001665, 27.1],
            [872.1, 0.000301, 26.99],
            [927.0, 0.0002205, 27.06],
            [981.8, 0.0001571, 27.12],
            [1010.0, 0.0003381, 26.94]
          ]
        }
      },
      "defaultPushOutVolume": 0
    }
  },
  "maxVolume": 1000,
  "minVolume": 100.0,
  "defaultTipracks": [
    "opentrons/opentrons_96_tiprack_1000ul/1",
    "opentrons/opentrons_96_filtertiprack_1000ul/1",
    "opentrons/geb_96_tiprack_1000ul/1"
  ]
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/liquid/single_channel/p50/lowVolumeDefault/3_4.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteLiquidPropertiesSchema.json",
  "supportedTips": {
    "t50": {
      "uiMaxFlowRate": 31.8,
      "defaultAspirateFlowRate": {
        "default": 31.8,
        "valuesByApiLevel": { "2.14": 31.8 }
      },
      "defaultDispenseFlowRate": {
        "default": 31.8,
        "valuesByApiLevel": { "2.14": 31.8 }
      },
      "defaultBlowOutFlowRate": {
        "default": 31.8,
        "valuesByApiLevel": { "2.14": 31.8 }
      },
      "defaultFlowAcceleration": 1200.0,
      "defaultTipLength": 57.9,
      "defaultReturnTipHeight": 0.71,
      "aspirate": {
        "default": {
          "1": [
            [0.36, 0.560999, 0.03366],
            [0.546667, 0.416654, 0.085624],
            [1.02, 0.333473, 0.131096],
            [1.3, 0.1045, 0.364649],
            [1.956667, 0.117611, 0.347604],
            [2.68, 0.039898, 0.499663],
            [3.013333, -0.026841, 0.678523],
            [3.36, 0.025988, 0.519331],
            [3.78, 0.028211, 0.511863],
            [4.396667, 0.082234, 0.307657],
            [5.073333, 0.010771, 0.621856],
            [5.88, 0.012027, 0.615482],
            [7.3, 0.00915, 0.632397],
            [9.086667, 0.007301, 0.645898],
            [10.143333, 0.005174, 0.665228],
            [13.76, 0.001967, 0.697758],
            [27.223333, 0.001039, 0.710524],
            [45.73, 0.000284, 0.731072]
          ]
        }
      },
      "dispense": {
        "default": {
          "1": [
            [0.36, 0.560999, 0.03366],
            [0.546667, 0.416654, 0.085624],
            [1.02, 0.333473, 0.131096],
            [1.3, 0.1045, 0.364649],
            [1.956667, 0.117611, 0.347604],
            [2.68, 0.039898, 0.499663],
            [3.013333, -0.026841, 0.678523],
            [3.36, 0.025988, 0.519331],
            [3.78, 0.028211, 0.511863],
            [4.396667, 0.082234, 0.307657],
            [5.073333, 0.010771, 0.621856],
            [5.88, 0.012027, 0.615482],
            [7.3, 0.00915, 0.632397],
            [9.086667, 0.007301, 0.645898],
            [10.143333, 0.005174, 0.665228],
            [13.76, 0.001967, 0.697758],
            [27.223333, 0.001039, 0.710524],
            [45.73, 0.000284, 0.731072]
          ]
        }
      },
      "defaultPushOutVolume": 7
    }
  },
  "maxVolume": 30,
  "minVolume": 1,
  "defaultTipracks": [
    "opentrons/opentrons_flex_96_tiprack_50ul/1",
    "opentrons/opentrons_flex_96_filtertiprack_50ul/1"
  ]
}
