=== Opentrons/opentrons/shared-data/pipette/schemas/2/pipetteGeometrySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "xyzArray": {
      "type": "array",
      "description": "Array of 3 numbers, [x, y, z]",
      "items": { "type": "number" },
      "minItems": 3,
      "maxItems": 3
    },
    "nozzleName": {
      "type": "string",
      "pattern": "[A-Z]+[0-9]+"
    },
    "rowName": {
      "type": "string",
      "pattern": "[A-Z]+",
      "description": "The name of a row of nozzles"
    },
    "columnName": {
      "type": "string",
      "pattern": "[0-9]+",
      "description": "The name of a column of nozzles"
    }
  },
  "type": "object",
  "required": ["$otSharedSchema", "nozzleOffset", "pathTo3D"],
  "additionalProperties": false,
  "properties": {
    "$otSharedSchema": {
      "type": "string",
      "description": "The path to a valid Opentrons shared schema relative to the shared-data directory, without its extension. For instance, #/pipette/schemas/2/pipetteGeometrySchema.json is a reference to this schema."
    },
    "nozzleOffset": { "$ref": "#/definitions/xyzArray" },
    "pipetteBoundingBoxOffsets": {
      "description": "Offsets from the pipette mount position to the back-left & front-right corners of the pipette's bounding box which includes the outer casing and all nozzles.",
      "type": "object",
      "properties": {
        "backLeftCorner": { "$ref": "#/definitions/xyzArray" },
        "frontRightCorner": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "pathTo3D": {
      "description": "path to the gltf file representing the 3D pipette model",
      "type": "string",
      "pattern": "^pipette/definitions/[2]/geometry/([a-z]*_[a-z]*)+/p[0-9]{2,4}/[a-z]*[.]gltf"
    },
    "orderedRows": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A row of nozzle keys",
        "required": ["key", "orderedNozzles"],
        "properties": {
          "key": { "$ref": "#/definitions/rowName" },
          "orderedNozzles": {
            "type": "array",
            "description": "The list of nozzle names in this row",
            "items": { "$ref": "#/definitions/nozzleName" }
          }
        }
      }
    },
    "orderedColumns": {
      "type": "array",
      "items": {
        "type": "object",
        "description": "A column of nozzle keys",
        "required": ["key", "orderedNozzles"],
        "properties": {
          "key": { "$ref": "#/definitions/columnName" },
          "orderedNozzles": {
            "type": "array",
            "description": "The list of nozzle names in this column",
            "items": { "$ref": "#/definitions/nozzleName" }
          }
        }
      }
    },
    "nozzleMap": {
      "type": "object",
      "description": "Unordered object of well objects with position and dimensional information",
      "additionalProperties": false,
      "patternProperties": {
        "[A-Z]+[0-9]+": { "$ref": "#/definitions/xyzArray" }
      }
    },
    "lldSettings": {
      "type": "object",
      "description": "Minimum space requirements for Liquid Level Detection to work properly",
      "additionalProperties": false,
      "properties": {
        "t50": {
          "type": "object",
          "properties": {
            "minHeight": { "type": "number" },
            "minVolume": { "type": "number" }
          }
        },
        "t200": {
          "type": "object",
          "properties": {
            "minHeight": { "type": "number" },
            "minVolume": { "type": "number" }
          }
        },
        "t1000": {
          "type": "object",
          "properties": {
            "minHeight": { "type": "number" },
            "minVolume": { "type": "number" }
          }
        }
      }
    }
  }
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/geometry/eight_channel/p300/1_3.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "nozzleOffset": [0.0, 31.5, 0.8],
  "pathTo3D": "pipette/definitions/2/geometry/eight_channel/p300/placeholder.gltf",
  "nozzleMap": {
    "A1": [0.0, 31.5, 0.8],
    "B1": [0.0, 40.5, 0.8],
    "C1": [0.0, 49.5, 0.8],
    "D1": [0.0, 58.5, 0.8],
    "E1": [0.0, 67.5, 0.8],
    "F1": [0.0, 76.5, 0.8],
    "G1": [0.0, 85.5, 0.8],
    "H1": [0.0, 94.5, 0.8]
  }
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/geometry/ninety_six_channel/p1000/1_0.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "pathTo3D": "pipette/definitions/2/geometry/ninety_six_channel/p1000/placeholder.gltf",
  "nozzleOffset": [-36.0, -25.5, -259.15],
  "pipetteBoundingBoxOffsets": {
    "backLeftCorner": [-67.0, -3.5, -259.15],
    "frontRightCorner": [94.0, -113.0, -259.15]
  },
  "orderedRows": [
    {
      "key": "A",
      "orderedNozzles": [
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12"
      ]
    },
    {
      "key": "B",
      "orderedNozzles": [
        "B1",
        "B2",
        "B3",
        "B4",
        "B5",
        "B6",
        "B7",
        "B8",
        "B9",
        "B10",
        "B11",
        "B12"
      ]
    },
    {
      "key": "C",
      "orderedNozzles": [
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C7",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12"
      ]
    },
    {
      "key": "D",
      "orderedNozzles": [
        "D1",
        "D2",
        "D3",
        "D4",
        "D5",
        "D6",
        "D7",
        "D8",
        "D9",
        "D10",
        "D11",
        "D12"
      ]
    },
    {
      "key": "E",
      "orderedNozzles": [
        "E1",
        "E2",
        "E3",
        "E4",
        "E5",
        "E6",
        "E7",
        "E8",
        "E9",
        "E10",
        "E11",
        "E12"
      ]
    },
    {
      "key": "F",
      "orderedNozzles": [
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12"
      ]
    },
    {
      "key": "G",
      "orderedNozzles": [
        "G1",
        "G2",
        "G3",
        "G4",
        "G5",
        "G6",
        "G7",
        "G8",
        "G9",
        "G10",
        "G11",
        "G12"
      ]
    },
    {
      "key": "H",
      "orderedNozzles": [
        "H1",
        "H2",
        "H3",
        "H4",
        "H5",
        "H6",
        "H7",
        "H8",
        "H9",
        "H10",
        "H11",
        "H12"
      ]
    }
  ],
  "orderedColumns": [
    {
      "key": "1",
      "orderedNozzles": ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"]
    },
    {
      "key": "2",
      "orderedNozzles": ["A2", "B2", "C2", "D2", "E2", "F2", "G2", "H2"]
    },
    {
      "key": "3",
      "orderedNozzles": ["A3", "B3", "C3", "D3", "E3", "F3", "G3", "H3"]
    },
    {
      "key": "4",
      "orderedNozzles": ["A4", "B4", "C4", "D4", "E4", "F4", "G4", "H4"]
    },
    {
      "key": "5",
      "orderedNozzles": ["A5", "B5", "C5", "D5", "E5", "F5", "G5", "H5"]
    },
    {
      "key": "6",
      "orderedNozzles": ["A6", "B6", "C6", "D6", "E6", "F6", "G6", "H6"]
    },
    {
      "key": "7",
      "orderedNozzles": ["A7", "B7", "C7", "D7", "E7", "F7", "G7", "H7"]
    },
    {
      "key": "8",
      "orderedNozzles": ["A8", "B8", "C8", "D8", "E8", "F8", "G8", "H8"]
    },
    {
      "key": "9",
      "orderedNozzles": ["A9", "B9", "C9", "D9", "E9", "F9", "G9", "H9"]
    },
    {
      "key": "10",
      "orderedNozzles": ["A10", "B10", "C10", "D10", "E10", "F10", "G10", "H10"]
    },
    {
      "key": "11",
      "orderedNozzles": ["A11", "B11", "C11", "D11", "E11", "F11", "G11", "H11"]
    },
    {
      "key": "12",
      "orderedNozzles": ["A12", "B12", "C12", "D12", "E12", "F12", "G12", "H12"]
    }
  ],
  "nozzleMap": {
    "A1": [-36.0, -25.5, -259.15],
    "A2": [-27.0, -25.5, -259.15],
    "A3": [-18.0, -25.5, -259.15],
    "A4": [-9.0, -25.5, -259.15],
    "A5": [0.0, -25.5, -259.15],
    "A6": [9.0, -25.5, -259.15],
    "A7": [18.0, -25.5, -259.15],
    "A8": [27.0, -25.5, -259.15],
    "A9": [36.0, -25.5, -259.15],
    "A10": [45.0, -25.5, -259.15],
    "A11": [54.0, -25.5, -259.15],
    "A12": [63.0, -25.5, -259.15],
    "B1": [-36.0, -34.5, -259.15],
    "B2": [-27.0, -34.5, -259.15],
    "B3": [-18.0, -34.5, -259.15],
    "B4": [-9.0, -34.5, -259.15],
    "B5": [0.0, -34.5, -259.15],
    "B6": [9.0, -34.5, -259.15],
    "B7": [18.0, -34.5, -259.15],
    "B8": [27.0, -34.5, -259.15],
    "B9": [36.0, -34.5, -259.15],
    "B10": [45.0, -34.5, -259.15],
    "B11": [54.0, -34.5, -259.15],
    "B12": [63.0, -34.5, -259.15],
    "C1": [-36.0, -43.5, -259.15],
    "C2": [-27.0, -43.5, -259.15],
    "C3": [-18.0, -43.5, -259.15],
    "C4": [-9.0, -43.5, -259.15],
    "C5": [0.0, -43.5, -259.15],
    "C6": [9.0, -43.5, -259.15],
    "C7": [18.0, -43.5, -259.15],
    "C8": [27.0, -43.5, -259.15],
    "C9": [36.0, -43.5, -259.15],
    "C10": [45.0, -43.5, -259.15],
    "C11": [54.0, -43.5, -259.15],
    "C12": [63.0, -43.5, -259.15],
    "D1": [-36.0, -52.5, -259.15],
    "D2": [-27.0, -52.5, -259.15],
    "D3": [-18.0, -52.5, -259.15],
    "D4": [-9.0, -52.5, -259.15],
    "D5": [0.0, -52.5, -259.15],
    "D6": [9.0, -52.5, -259.15],
    "D7": [18.0, -52.5, -259.15],
    "D8": [27.0, -52.5, -259.15],
    "D9": [36.0, -52.5, -259.15],
    "D10": [45.0, -52.5, -259.15],
    "D11": [54.0, -52.5, -259.15],
    "D12": [63.0, -52.5, -259.15],
    "E1": [-36.0, -61.5, -259.15],
    "E2": [-27.0, -61.5, -259.15],
    "E3": [-18.0, -61.5, -259.15],
    "E4": [-9.0, -61.5, -259.15],
    "E5": [0.0, -61.5, -259.15],
    "E6": [9.0, -61.5, -259.15],
    "E7": [18.0, -61.5, -259.15],
    "E8": [27.0, -61.5, -259.15],
    "E9": [36.0, -61.5, -259.15],
    "E10": [45.0, -61.5, -259.15],
    "E11": [54.0, -61.5, -259.15],
    "E12": [63.0, -61.5, -259.15],
    "F1": [-36.0, -70.5, -259.15],
    "F2": [-27.0, -70.5, -259.15],
    "F3": [-18.0, -70.5, -259.15],
    "F4": [-9.0, -70.5, -259.15],
    "F5": [0.0, -70.5, -259.15],
    "F6": [9.0, -70.5, -259.15],
    "F7": [18.0, -70.5, -259.15],
    "F8": [27.0, -70.5, -259.15],
    "F9": [36.0, -70.5, -259.15],
    "F10": [45.0, -70.5, -259.15],
    "F11": [54.0, -70.5, -259.15],
    "F12": [63.0, -70.5, -259.15],
    "G1": [-36.0, -79.5, -259.15],
    "G2": [-27.0, -79.5, -259.15],
    "G3": [-18.0, -79.5, -259.15],
    "G4": [-9.0, -79.5, -259.15],
    "G5": [0.0, -79.5, -259.15],
    "G6": [9.0, -79.5, -259.15],
    "G7": [18.0, -79.5, -259.15],
    "G8": [27.0, -79.5, -259.15],
    "G9": [36.0, -79.5, -259.15],
    "G10": [45.0, -79.5, -259.15],
    "G11": [54.0, -79.5, -259.15],
    "G12": [63.0, -79.5, -259.15],
    "H1": [-36.0, -88.5, -259.15],
    "H2": [-27.0, -88.5, -259.15],
    "H3": [-18.0, -88.5, -259.15],
    "H4": [-9.0, -88.5, -259.15],
    "H5": [0.0, -88.5, -259.15],
    "H6": [9.0, -88.5, -259.15],
    "H7": [18.0, -88.5, -259.15],
    "H8": [27.0, -88.5, -259.15],
    "H9": [36.0, -88.5, -259.15],
    "H10": [45.0, -88.5, -259.15],
    "H11": [54.0, -88.5, -259.15],
    "H12": [63.0, -88.5, -259.15]
  },
  "lldSettings": {}
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/geometry/eight_channel/p1000/3_4.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "pathTo3D": "pipette/definitions/2/geometry/eight_channel/p50/placeholder.gltf",
  "nozzleOffset": [-8.0, -16.0, -259.15],
  "pipetteBoundingBoxOffsets": {
    "backLeftCorner": [-38.5, 0.0, -259.15],
    "frontRightCorner": [11.5, -95.0, -259.15]
  },
  "orderedRows": [
    {
      "key": "A",
      "orderedNozzles": ["A1"]
    },
    {
      "key": "B",
      "orderedNozzles": ["B1"]
    },
    { "key": "C", "orderedNozzles": ["C1"] },
    { "key": "D", "orderedNozzles": ["D1"] },
    { "key": "E", "orderedNozzles": ["E1"] },
    { "key": "F", "orderedNozzles": ["F1"] },
    { "key": "G", "orderedNozzles": ["G1"] },
    { "key": "H", "orderedNozzles": ["H1"] }
  ],
  "orderedColumns": [
    {
      "key": "1",
      "orderedNozzles": ["A1", "B1", "C1", "D1", "E1", "F1", "G1", "H1"]
    }
  ],
  "nozzleMap": {
    "A1": [-8.0, -16.0, -259.15],
    "B1": [-8.0, -25.0, -259.15],
    "C1": [-8.0, -34.0, -259.15],
    "D1": [-8.0, -43.0, -259.15],
    "E1": [-8.0, -52.0, -259.15],
    "F1": [-8.0, -61.0, -259.15],
    "G1": [-8.0, -70.0, -259.15],
    "H1": [-8.0, -79.0, -259.15]
  },
  "lldSettings": {
    "t50": {
      "minHeight": 1.0,
      "minVolume": 0
    },
    "t200": {
      "minHeight": 1.0,
      "minVolume": 0
    },
    "t1000": {
      "minHeight": 1.5,
      "minVolume": 0
    }
  }
}

=== Opentrons/opentrons/shared-data/pipette/definitions/2/geometry/single_channel/p50/3_6.json
{
  "$otSharedSchema": "#/pipette/schemas/2/pipetteGeometrySchema.json",
  "pathTo3D": "pipette/definitions/2/geometry/single_channel/p50/placeholder.gltf",
  "nozzleOffset": [-8.0, -22.0, -259.15],
  "pipetteBoundingBoxOffsets": {
    "backLeftCorner": [-8.0, -22.0, -259.15],
    "frontRightCorner": [-8.0, -22.0, -259.15]
  },
  "orderedRows": [{ "key": "A", "orderedNozzles": ["A1"] }],
  "orderedColumns": [{ "key": "1", "orderedNozzles": ["A1"] }],
  "nozzleMap": {
    "A1": [-8.0, -22.0, -259.15]
  },
  "lldSettings": {
    "t50": {
      "minHeight": 1.0,
      "minVolume": 0
    }
  }
}
